export interface LocationPageData {
  slug: string;
  country: string;
  countryCode: string; // ISO 3166-1 alpha-2
  flag: string;
  heroTitle: string;
  heroHighlight: string;
  heroDescription: string;
  stats: { value: string; label: string }[];
  localBenefits: string[];
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string;
}

export const locationPages: LocationPageData[] = [
  {
    slug: "indoor-playground-equipment-usa",
    country: "United States",
    countryCode: "US",
    flag: "🇺🇸",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for the United States",
    heroDescription: "ASTM F1918 certified commercial indoor playground equipment designed for the US market. Custom FEC solutions with nationwide delivery and installation support.",
    stats: [
      { value: "500+", label: "US Projects Completed" },
      { value: "48", label: "States Served" },
      { value: "ASTM", label: "F1918 Certified" },
      { value: "15+", label: "Years in US Market" },
    ],
    localBenefits: [
      "ASTM F1918 & CPSC compliant equipment",
      "US warehouse for faster shipping",
      "ADA-accessible design options",
      "Local installation partners across 48 states",
    ],
    metaTitle: "Indoor Playground Equipment USA | ASTM Certified",
    metaDescription: "Buy commercial indoor playground equipment in the USA. ASTM F1918 certified, custom designs, nationwide delivery. Get a free quote from NinescapeLand.",
    metaKeywords: "indoor playground equipment USA, commercial playground USA, ASTM certified playground, FEC equipment America",
  },
  {
    slug: "indoor-playground-equipment-uk",
    country: "United Kingdom",
    countryCode: "GB",
    flag: "🇬🇧",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for the United Kingdom",
    heroDescription: "EN 1176 certified indoor play equipment built for the UK market. From soft play centres to full FEC builds with UK-based support.",
    stats: [
      { value: "200+", label: "UK Projects" },
      { value: "EN 1176", label: "Certified" },
      { value: "£0", label: "Free 3D Design" },
      { value: "4-6wk", label: "UK Delivery" },
    ],
    localBenefits: [
      "EN 1176 & BS EN 1177 compliant",
      "UK customs & VAT guidance included",
      "Installation teams across England, Scotland & Wales",
      "Free on-site measurement service",
    ],
    metaTitle: "Indoor Playground Equipment UK | EN 1176 Certified",
    metaDescription: "Commercial indoor playground equipment supplier for the UK. EN 1176 certified, bespoke designs, nationwide installation. Request your free quote.",
    metaKeywords: "indoor playground equipment UK, soft play equipment, commercial playground supplier UK, EN 1176 certified",
  },
  {
    slug: "indoor-playground-equipment-uae",
    country: "United Arab Emirates",
    countryCode: "AE",
    flag: "🇦🇪",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for the UAE",
    heroDescription: "Premium indoor play solutions for Dubai, Abu Dhabi and across the Emirates. Custom-designed entertainment centres for malls, hotels, and family zones.",
    stats: [
      { value: "150+", label: "UAE Projects" },
      { value: "TUV", label: "SÜD Certified" },
      { value: "50+", label: "Mall Installations" },
      { value: "24/7", label: "Gulf Support" },
    ],
    localBenefits: [
      "TUV SÜD & EN 1176 certified",
      "Designed for mall and hotel environments",
      "Arabic-speaking project managers",
      "Dubai-based logistics hub for fast delivery",
    ],
    metaTitle: "Indoor Playground Equipment UAE | Dubai & Abu Dhabi",
    metaDescription: "Top indoor playground equipment supplier in UAE. Custom FEC solutions for Dubai malls & hotels. TUV certified with local support. Free 3D design.",
    metaKeywords: "indoor playground equipment UAE, playground supplier Dubai, FEC equipment Abu Dhabi, mall playground UAE",
  },
  {
    slug: "indoor-playground-equipment-saudi-arabia",
    country: "Saudi Arabia",
    countryCode: "SA",
    flag: "🇸🇦",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Saudi Arabia",
    heroDescription: "Family entertainment centre equipment for Saudi Vision 2030. Certified play solutions for Riyadh, Jeddah, and emerging entertainment districts.",
    stats: [
      { value: "100+", label: "KSA Projects" },
      { value: "Vision", label: "2030 Aligned" },
      { value: "SASO", label: "Compliant" },
      { value: "Free", label: "3D Design" },
    ],
    localBenefits: [
      "SASO & GCC standards compliant",
      "Aligned with Vision 2030 entertainment goals",
      "Arabic-speaking support team",
      "Experience with Saudi mega-projects",
    ],
    metaTitle: "Indoor Playground Equipment Saudi Arabia | KSA",
    metaDescription: "Commercial playground equipment for Saudi Arabia. Vision 2030 aligned FEC solutions for Riyadh & Jeddah. SASO compliant. Free quote available.",
    metaKeywords: "indoor playground equipment Saudi Arabia, FEC equipment KSA, playground Riyadh, entertainment centre Jeddah",
  },
  {
    slug: "indoor-playground-equipment-australia",
    country: "Australia",
    countryCode: "AU",
    flag: "🇦🇺",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Australia",
    heroDescription: "AS 4685 compliant commercial play equipment for Australia. Custom indoor playgrounds, trampoline parks, and ninja courses shipped to every state.",
    stats: [
      { value: "120+", label: "AU Projects" },
      { value: "AS 4685", label: "Compliant" },
      { value: "6", label: "States & Territories" },
      { value: "Free", label: "Site Survey" },
    ],
    localBenefits: [
      "AS 4685 & AS/NZS standards compliant",
      "Sydney warehouse for local dispatch",
      "Installation partners in all major cities",
      "Bushfire-rated material options available",
    ],
    metaTitle: "Indoor Playground Equipment Australia | AS 4685",
    metaDescription: "Buy commercial indoor playground equipment in Australia. AS 4685 compliant, custom designs for Sydney, Melbourne & Brisbane. Free site survey.",
    metaKeywords: "indoor playground equipment Australia, commercial playground Sydney, AS 4685 playground, FEC equipment Melbourne",
  },
  {
    slug: "indoor-playground-equipment-canada",
    country: "Canada",
    countryCode: "CA",
    flag: "🇨🇦",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Canada",
    heroDescription: "CSA & ASTM certified indoor play equipment for the Canadian market. Bilingual project support with delivery from coast to coast.",
    stats: [
      { value: "80+", label: "Canadian Projects" },
      { value: "CSA", label: "Certified" },
      { value: "10", label: "Provinces Served" },
      { value: "EN/FR", label: "Bilingual Support" },
    ],
    localBenefits: [
      "CSA Z614 & ASTM F1918 certified",
      "Bilingual (English/French) support",
      "Toronto warehouse for faster dispatch",
      "Cold-climate durable materials",
    ],
    metaTitle: "Indoor Playground Equipment Canada | CSA Certified",
    metaDescription: "Commercial indoor playground equipment for Canada. CSA Z614 certified, bilingual support, coast-to-coast delivery. Request your free quote.",
    metaKeywords: "indoor playground equipment Canada, CSA certified playground, FEC equipment Toronto, commercial playground Vancouver",
  },
  {
    slug: "indoor-playground-equipment-germany",
    country: "Germany",
    countryCode: "DE",
    flag: "🇩🇪",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Germany",
    heroDescription: "TUV SÜD & EN 1176 certified Spielplatzgeräte for the German market. Premium indoor play solutions with German-speaking project management.",
    stats: [
      { value: "90+", label: "German Projects" },
      { value: "TUV SÜD", label: "Certified" },
      { value: "DIN EN", label: "1176 Compliant" },
      { value: "Free", label: "Planung" },
    ],
    localBenefits: [
      "TUV SÜD & DIN EN 1176 certified",
      "German-speaking project managers",
      "EU import & customs handling included",
      "Hamburg port logistics streamlined",
    ],
    metaTitle: "Indoor Playground Equipment Germany | TUV Certified",
    metaDescription: "Kommerzielle Indoor-Spielplatzgeräte für Deutschland. TUV SÜD & EN 1176 zertifiziert. Kostenlose 3D-Planung. NinescapeLand.",
    metaKeywords: "indoor playground equipment Germany, Spielplatzgeräte, TUV certified playground, indoor Spielplatz Deutschland",
  },
  {
    slug: "indoor-playground-equipment-india",
    country: "India",
    countryCode: "IN",
    flag: "🇮🇳",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for India",
    heroDescription: "Commercial indoor playground and FEC equipment for India's booming entertainment market. Custom solutions for malls, resorts, and standalone centres.",
    stats: [
      { value: "180+", label: "India Projects" },
      { value: "BIS", label: "Standard Ready" },
      { value: "28", label: "States Covered" },
      { value: "Free", label: "3D Design" },
    ],
    localBenefits: [
      "BIS safety standards compatible",
      "Competitive pricing for Indian market",
      "Hindi & English support available",
      "Installation teams in Mumbai, Delhi, Bangalore",
    ],
    metaTitle: "Indoor Playground Equipment India | Commercial FEC",
    metaDescription: "Buy indoor playground equipment in India. Custom FEC solutions for malls & resorts. Competitive pricing with free 3D design. NinescapeLand.",
    metaKeywords: "indoor playground equipment India, commercial playground Mumbai, FEC equipment Delhi, play zone equipment Bangalore",
  },
  {
    slug: "indoor-playground-equipment-mexico",
    country: "Mexico",
    countryCode: "MX",
    flag: "🇲🇽",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Mexico",
    heroDescription: "Equipos de parques infantiles interiores para México. Diseños personalizados con certificación internacional para centros comerciales y FECs.",
    stats: [
      { value: "70+", label: "Mexico Projects" },
      { value: "NOM", label: "Compliant" },
      { value: "ASTM", label: "Certified" },
      { value: "Free", label: "Diseño 3D" },
    ],
    localBenefits: [
      "NOM & ASTM certified equipment",
      "Spanish-speaking project managers",
      "Mexico City logistics hub",
      "Experience with Latin American regulations",
    ],
    metaTitle: "Indoor Playground Equipment Mexico | NOM Certified",
    metaDescription: "Equipos de parques infantiles para México. Certificación NOM y ASTM. Diseño 3D gratuito. Entrega e instalación nacional. NinescapeLand.",
    metaKeywords: "indoor playground equipment Mexico, parques infantiles México, FEC equipment CDMX, playground equipment Monterrey",
  },
  {
    slug: "indoor-playground-equipment-brazil",
    country: "Brazil",
    countryCode: "BR",
    flag: "🇧🇷",
    heroTitle: "Indoor Playground Equipment",
    heroHighlight: "for Brazil",
    heroDescription: "Equipamentos para playgrounds internos no Brasil. Soluções personalizadas com certificação ABNT para shopping centers e centros de entretenimento.",
    stats: [
      { value: "60+", label: "Brazil Projects" },
      { value: "ABNT", label: "NBR Certified" },
      { value: "INMETRO", label: "Ready" },
      { value: "Free", label: "Projeto 3D" },
    ],
    localBenefits: [
      "ABNT NBR 16071 certified equipment",
      "Portuguese-speaking support team",
      "Santos port logistics optimized",
      "Experience with Brazilian import requirements",
    ],
    metaTitle: "Indoor Playground Equipment Brazil | ABNT Certified",
    metaDescription: "Equipamentos para playgrounds internos no Brasil. Certificação ABNT, designs personalizados, instalação nacional. Solicite seu orçamento grátis.",
    metaKeywords: "indoor playground equipment Brazil, playground infantil Brasil, ABNT certified playground, FEC equipment São Paulo",
  },
];

export const getLocationBySlug = (slug: string): LocationPageData | undefined =>
  locationPages.find((l) => l.slug === slug);
