import type { StableSolutionPageProps } from "@/pages/StableSolutionPage";
import { heroImages, productImages, projectImages } from "@/config/galleryImages";

const sources = {
  cpsc: {
    label: "Public Playground Safety Handbook (CPSC 325)",
    publisher: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/s3fs-public/325.pdf",
    note: "Use zones, surfacing, inspection and maintenance guidance.",
  },
  astmF1487: {
    label: "ASTM F1487 — Playground Equipment for Public Use",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1487-21.html",
  },
  astmF1918: {
    label: "ASTM F1918 — Soft Contained Play Equipment",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1918-12r19.html",
  },
  astmF2970: {
    label: "ASTM F2970 — Trampoline Courts",
    publisher: "ASTM International",
    url: "https://www.astm.org/f2970-15.html",
  },
  en1176: {
    label: "EN 1176-7 — Guidance on Installation, Inspection, Maintenance and Operation",
    publisher: "CEN-CENELEC",
    url: "https://www.cencenelec.eu/",
  },
  cdcCleaning: {
    label: "Cleaning and Disinfecting Your Facility",
    publisher: "U.S. Centers for Disease Control and Prevention",
    url: "https://www.cdc.gov/hygiene/cleaning/facility.html",
    note: "Difference between cleaning, sanitising and disinfecting surfaces.",
  },
  epaListN: {
    label: "Disinfectants for Use Against SARS-CoV-2 (List N)",
    publisher: "U.S. Environmental Protection Agency",
    url: "https://www.epa.gov/pesticide-registration/disinfectants-use-against-sars-cov-2-list-n",
  },
  osha: {
    label: "Fall Protection and Construction Safety",
    publisher: "U.S. Occupational Safety and Health Administration",
    url: "https://www.osha.gov/fall-protection",
  },
  nfpa101: {
    label: "NFPA 101 — Life Safety Code",
    publisher: "National Fire Protection Association",
    url: "https://www.nfpa.org/codes-and-standards/nfpa-101-standard-development/101",
  },
  sba: {
    label: "10 Steps to Start Your Business",
    publisher: "U.S. Small Business Administration",
    url: "https://www.sba.gov/business-guide/10-steps-start-your-business",
  },
  hhsGuidelines: {
    label: "Physical Activity Guidelines for Americans, 2nd Edition",
    publisher: "U.S. Department of Health and Human Services",
    url: "https://health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines",
  },
};

const cluster = {
  installation: { label: "Turnkey installation services", href: "/turnkey-indoor-playground-installation-services" },
  maintenance: { label: "Maintenance and cleaning guide", href: "/indoor-playground-maintenance-and-cleaning-guide" },
  kidsNinja: { label: "Ninja warrior course for kids", href: "/ninja-warrior-course-for-kids-indoor-playground" },
  trampolineLayout: { label: "Trampoline park layout design", href: "/indoor-trampoline-park-layout-design" },
  startBusiness: { label: "How to start an indoor playground business", href: "/how-to-start-an-indoor-playground-business-2026" },
};

export const weeklyAggregationPagesB10: Record<string, StableSolutionPageProps> = {
  installation: {
    slug: "turnkey-indoor-playground-installation-services",
    title: "Turnkey Indoor Playground Installation Services",
    metaTitle: "Turnkey Indoor Playground Installation Services",
    metaDescription: "What happens after your equipment ships: site readiness, customs, crew size, install timeline and the handover checklist for a turnkey indoor playground.",
    keywords: ["turnkey indoor playground installation services", "indoor playground installation", "turnkey indoor playground", "playground installation checklist"],
    kicker: "Site Readiness · Install Crew · Timeline · Handover",
    description: "Design and price get most of the attention, but projects are won or lost on site. This guide covers the part that starts when containers arrive: what the building must be ready for, how many installers you need, how long each equipment type takes, and the inspection checklist you sign before opening day.",
    primaryCta: "Plan My Installation",
    secondaryCta: "See the Install Timeline",
    heroImage: heroImages.indoorPlayground,
    heroImageAlt: "3D perspective render of a multi-level indoor playground structure during final installation",
    metrics: [
      { value: "7–21 days", label: "Typical on-site install window" },
      { value: "3–6", label: "Installers per crew for most projects" },
      { value: "≥ 4.5 m", label: "Clear height for most multi-level structures" },
      { value: "40+", label: "Points on the handover checklist" },
    ],
    frameworkTitle: "The Five Installation Phases",
    frameworkIntro: "Each phase has a gate. Moving to the next one before the gate is cleared is the most common cause of delay and re-work.",
    framework: [
      { title: "1. Site readiness check", desc: "Floor level within tolerance, clear height confirmed, columns and sprinklers measured, power points placed. We send a readiness form 30 days before shipping." },
      { title: "2. Delivery and customs", desc: "Containers are cleared with the packing list and certificates. Unloading needs a forklift or pallet jack and a dry staging area close to the hall." },
      { title: "3. Frame and structure", desc: "Steel columns, decks and beams go up first, levelled and anchored. This is the phase that needs the most installers." },
      { title: "4. Soft parts and attractions", desc: "Padding, nets, slides, trampoline beds, ninja obstacles and themed panels are fitted after the frame passes a torque check." },
      { title: "5. Inspection and handover", desc: "Use zones, gaps, fixings and surfacing are checked against the design, then staff are trained on daily checks before the keys change hands." },
    ],
    equipmentTitle: "What a Turnkey Installation Package Includes",
    equipmentIntro: "Turnkey means one party is responsible from site check to handover. These are the deliverables you should see in writing.",
    equipment: [
      { title: "Installation drawings", desc: "Anchor plans, column positions and section heights issued before production so the site can be prepared." },
      { title: "Supervised install crew", desc: "A lead supervisor from the factory plus local or factory installers, depending on project size and budget." },
      { title: "Tool and fixings kit", desc: "Shipped with the order so work never waits on a missing anchor bolt or special wrench." },
      { title: "Spare parts box", desc: "Common padding, net ties, bolts and covers held on site for the first months of operation." },
      { title: "Staff training", desc: "Daily, weekly and monthly inspection routines, with sign-off sheets your team uses from day one." },
      { title: "Handover documents", desc: "Certificates, as-built drawings, maintenance manual and warranty registration in one file." },
    ],
    gallery: [
      { src: projectImages.indoorProject, alt: "Indoor playground structure with steel frame and padded decks", caption: "Frame and decks installed and levelled." },
      { src: projectImages.trampolineProject, alt: "Trampoline court with beds and padding fitted", caption: "Trampoline beds fitted after frame checks." },
      { src: projectImages.fecCenter, alt: "Completed family entertainment centre ready for handover", caption: "Final inspection before opening." },
    ],
    specTable: {
      heading: "Typical On-Site Installation Time by Project Type",
      intro: "Planning ranges for a trained crew working standard shifts in a ready building.",
      caption: "Indoor playground installation time, crew size and site requirements by project type",
      columns: ["Project type", "Area", "Crew size", "Install days", "Key site requirement"],
      rows: [
        ["Soft play structure", "100–300 m²", "3–4", "7–10", "Level floor, 3.5–5 m clear height"],
        ["Multi-level playground", "300–800 m²", "4–6", "10–18", "Anchor points, ≥ 4.5 m clear height"],
        ["Trampoline park", "500–1,500 m²", "4–6", "12–20", "Flat slab, foam pit excavation or raised deck"],
        ["Ninja course", "150–400 m²", "3–4", "6–10", "Overhead load capacity confirmed"],
        ["Full FEC (mixed)", "1,000–3,000 m²", "6–10", "18–30", "Phased handover by zone"],
      ],
      footnote: "Ranges assume the site passed the readiness check. Customs delays, unfinished ceilings or late electrics extend the timeline.",
    },
    audienceTitle: "Who Needs a Turnkey Installation",
    audienceIntro: "Turnkey is most valuable when the owner does not have an in-house construction team.",
    audience: [
      { title: "First-time operators", desc: "One contract and one point of contact from design to opening day." },
      { title: "Overseas investors", desc: "Factory supervision on site means the structure is built exactly as engineered." },
      { title: "Mall and retail landlords", desc: "Fixed install windows that fit around tenant fit-out schedules." },
      { title: "Multi-site chains", desc: "The same crew and checklist across every location keeps quality consistent." },
    ],
    related: [
      cluster.startBusiness,
      cluster.trampolineLayout,
      cluster.maintenance,
      cluster.kidsNinja,
      { label: "Free 3D design for play centres", href: "/free-3d-design-for-indoor-play-center" },
      { label: "ASTM certified play structures", href: "/astm-certified-indoor-playground-structures" },
    ],
    faq: [
      { title: "What does turnkey indoor playground installation include?", desc: "Site readiness checks, delivery coordination, a supervised install crew, tools and fixings, staff training, inspection and a full handover file." },
      { title: "How long does installation take?", desc: "Most projects take 7–21 days on site once the building is ready. Large mixed FECs can take 3–4 weeks and are often handed over zone by zone." },
      { title: "What clear height do I need?", desc: "Single-level soft play can work at about 3.5 m. Multi-level structures usually need 4.5 m or more, measured below sprinklers, ducts and lights." },
      { title: "Can local workers install the equipment?", desc: "Yes. Many projects use a local crew led by a factory supervisor, which reduces travel cost while keeping quality control." },
      { title: "What should be finished before installers arrive?", desc: "Floor, ceiling, lighting, sprinklers and main electrics. Painting and flooring outside the play area can continue in parallel." },
      { title: "Who inspects the playground before opening?", desc: "The install supervisor runs the internal checklist; many markets also require an independent inspector against ASTM or EN 1176 before opening." },
      { title: "Does NinescapeLand provide installation abroad?", desc: "Yes. We send supervisors or full crews to project sites worldwide and provide remote video guidance for smaller orders." },
    ],
    sources: [sources.en1176, sources.astmF1487, sources.astmF2970, sources.osha, sources.nfpa101],
  },

  maintenance: {
    slug: "indoor-playground-maintenance-and-cleaning-guide",
    title: "Indoor Playground Maintenance and Cleaning Guide",
    metaTitle: "Indoor Playground Maintenance & Cleaning Guide",
    metaDescription: "Daily, weekly and monthly cleaning and inspection routines for soft play, ball pits, nets and trampoline beds, with a ready-to-use operator checklist.",
    keywords: ["indoor playground maintenance and cleaning guide", "indoor playground cleaning", "soft play cleaning schedule", "indoor playground inspection checklist"],
    kicker: "Daily · Weekly · Monthly · Component-by-Component",
    description: "A clean, well-checked playground is what parents notice and what insurers ask about. This guide gives operators a working schedule: what to wipe, sanitise and inspect every day, week and month, how to treat each material — PVC padding, ball pits, nets, trampoline beds, slides — and how to record it so you can prove it.",
    primaryCta: "Get the Maintenance Checklist",
    secondaryCta: "See the Cleaning Schedule",
    heroImage: productImages.softPlay,
    heroImageAlt: "3D perspective render of a clean soft play area with padded structure and ball pit",
    metrics: [
      { value: "3 tiers", label: "Daily, weekly and monthly routines" },
      { value: "6", label: "Component types with their own method" },
      { value: "15–30 min", label: "Typical daily pre-opening check" },
      { value: "1×/yr", label: "Independent annual inspection" },
    ],
    frameworkTitle: "Clean, Sanitise, Disinfect, Inspect",
    frameworkIntro: "Four different jobs that are often confused. Each one has a place in the schedule.",
    framework: [
      { title: "1. Clean", desc: "Remove dust, crumbs and visible dirt with a neutral detergent. Sanitiser and disinfectant only work on surfaces that are already clean." },
      { title: "2. Sanitise", desc: "Lower germs on high-touch surfaces — handrails, slide entries, tunnel windows — to a safe level, usually daily." },
      { title: "3. Disinfect", desc: "Use a registered product with the correct contact time after illness incidents or on a fixed weekly cycle." },
      { title: "4. Inspect", desc: "Look for torn covers, loose fixings, frayed nets and worn surfacing. Log what you found and what you fixed." },
    ],
    equipmentTitle: "Cleaning Method by Component",
    equipmentIntro: "Each material wears differently. Using the wrong product shortens its life.",
    equipment: [
      { title: "PVC padding and soft modules", desc: "Wipe with mild detergent, then a non-abrasive sanitiser. Avoid solvent cleaners that harden the PVC and cause cracking." },
      { title: "Ball pits", desc: "Remove debris daily, wash balls in a ball-cleaning machine or mesh bags on a fixed cycle, and vacuum the pit floor." },
      { title: "Nets and ropes", desc: "Vacuum and spot clean; check every tie point. Replace a net section as soon as one strand is broken." },
      { title: "Trampoline beds", desc: "Vacuum the jumping surface, check springs and edge padding, and confirm no gaps open at the frame." },
      { title: "Slides", desc: "Clean with a slide-safe product that keeps the speed consistent; inspect joints for steps or sharp edges." },
      { title: "Flooring and mats", desc: "Vacuum and damp mop; check seams and impact mats under every fall zone." },
    ],
    gallery: [
      { src: projectImages.softPlayProject, alt: "Soft play padding and slides in a clean indoor play area", caption: "Wipe-clean PVC padding on high-touch points." },
      { src: projectImages.indoorProject, alt: "Indoor playground nets and tunnels ready for inspection", caption: "Nets and tie points on the weekly check." },
      { src: projectImages.trampolineProject, alt: "Trampoline court with edge padding", caption: "Trampoline beds and edge pads checked daily." },
    ],
    specTable: {
      heading: "Indoor Playground Cleaning and Inspection Schedule",
      intro: "A starting schedule for a busy commercial venue. Increase frequency during peak seasons.",
      caption: "Daily, weekly and monthly maintenance tasks by component",
      columns: ["Component", "Daily", "Weekly", "Monthly"],
      rows: [
        ["Soft padding", "Wipe and sanitise touch points", "Full wipe-down; check covers", "Check foam and zips for wear"],
        ["Ball pit", "Remove debris", "Vacuum pit floor", "Wash or rotate all balls"],
        ["Nets and ropes", "Visual check", "Vacuum; check tie points", "Tension and fixing check"],
        ["Trampolines", "Bed and pad visual check", "Vacuum; springs check", "Frame bolts torque check"],
        ["Slides", "Wipe entry and exit", "Full clean", "Joint and fixing inspection"],
        ["Floor and mats", "Vacuum and mop", "Seam check", "Impact mat condition review"],
      ],
      footnote: "Follow the manufacturer's manual and local health rules. Record each task with date, staff name and any defects found.",
    },
    audienceTitle: "Who Uses This Guide",
    audienceIntro: "Written for the people who open the venue every morning.",
    audience: [
      { title: "Venue managers", desc: "Turn maintenance into a scheduled routine instead of a reaction to complaints." },
      { title: "Daycare and preschool staff", desc: "Meet hygiene inspection requirements with written records." },
      { title: "Mall operators", desc: "Keep a shared play area presentable through high footfall." },
      { title: "Owners preparing for insurance", desc: "Show inspection logs when renewing cover or after an incident." },
    ],
    related: [
      cluster.installation,
      cluster.startBusiness,
      cluster.trampolineLayout,
      cluster.kidsNinja,
      { label: "Maintenance and warranty", href: "/maintenance-warranty" },
      { label: "Hygienic playground for infants", href: "/hygienic-indoor-playground-for-infants" },
    ],
    faq: [
      { title: "How often should an indoor playground be cleaned?", desc: "High-touch surfaces daily, a full wipe-down weekly and deep cleaning of ball pits and soft parts monthly, with more frequent cycles in busy periods." },
      { title: "What should I use to clean soft play equipment?", desc: "A neutral detergent followed by a non-abrasive sanitiser suitable for PVC. Avoid solvents and bleach-heavy mixes that damage the covers." },
      { title: "How do I clean a ball pit?", desc: "Remove debris daily and wash the balls in a ball-cleaning machine or mesh bags on a fixed cycle; vacuum the pit floor before refilling." },
      { title: "What is the difference between sanitising and disinfecting?", desc: "Sanitising lowers germs to a safe level; disinfecting kills most germs with a registered product and a set contact time." },
      { title: "What should a daily inspection cover?", desc: "Torn covers, loose fixings, broken net strands, gaps at trampoline frames, slide joints and impact mats under fall zones." },
      { title: "Do I need an independent inspection?", desc: "Most operators book an annual independent inspection against ASTM or EN 1176, and insurers often require it." },
      { title: "Does NinescapeLand supply spare parts?", desc: "Yes. We supply replacement covers, nets, padding and fixings, and every project ships with a starter spare parts box." },
    ],
    sources: [sources.cdcCleaning, sources.epaListN, sources.en1176, sources.astmF1918, sources.cpsc],
  },

  kidsNinja: {
    slug: "ninja-warrior-course-for-kids-indoor-playground",
    title: "Ninja Warrior Course for Kids in Indoor Playgrounds",
    metaTitle: "Ninja Warrior Course for Kids | Indoor Playground",
    metaDescription: "Kids ninja warrior course design by age band: obstacle types, heights, landing mats and timed-run and party formats for indoor playgrounds.",
    keywords: ["ninja warrior course for kids", "kids ninja course", "indoor ninja warrior course", "ninja obstacles for kids"],
    kicker: "Ages 4–12 · Three Age Bands · Obstacles · Party Formats",
    description: "Kids want the TV ninja experience, but a 5-year-old and an 11-year-old need very different obstacles. This page splits a kids ninja warrior course into three age bands, lists the obstacles, heights and mats for each, and shows how timed runs and birthday parties turn the course into steady revenue inside an indoor playground.",
    primaryCta: "Design My Kids Ninja Course",
    secondaryCta: "See Age-Band Obstacles",
    heroImage: heroImages.ninjaCourse,
    heroImageAlt: "3D perspective render of a kids ninja warrior course with swinging rings and balance steps",
    metrics: [
      { value: "3 bands", label: "4–6, 7–9 and 10–12 years" },
      { value: "8–14", label: "Obstacles in a typical kids lane" },
      { value: "150–400 m²", label: "Common floor area" },
      { value: "60–90 s", label: "Average timed run" },
    ],
    frameworkTitle: "How to Build a Kids Ninja Course by Age Band",
    frameworkIntro: "Separate bands keep younger children safe and older children challenged. Many venues run a junior and a senior lane side by side.",
    framework: [
      { title: "Ages 4–6: Junior lane", desc: "Floor-level balance steps, low cargo nets, short monkey bars with feet near the mat and soft foam walls. Success on every attempt matters more than difficulty." },
      { title: "Ages 7–9: Intermediate lane", desc: "Swinging rings, quintuple steps, a small warped wall and rope climbs at moderate height. Introduce a stopwatch and simple leaderboards." },
      { title: "Ages 10–12: Senior lane", desc: "Salmon ladder trainers, lache bars, cliffhanger ledges and a taller warped wall. Timed runs, heats and seasonal leagues keep them returning." },
      { title: "Shared finish zone", desc: "A buzzer, podium and viewing area for parents. The finish is where photos happen and where birthday bookings are sold." },
    ],
    equipmentTitle: "Popular Kids Ninja Obstacles",
    equipmentIntro: "Modular frames let you swap obstacles each season so regular visitors always find something new.",
    equipment: [
      { title: "Quintuple steps", desc: "Angled stepping blocks that train balance and momentum; heights scaled per lane." },
      { title: "Swinging rings and ropes", desc: "Grip and swing timing; ring spacing set to the arm span of each age band." },
      { title: "Warped wall", desc: "Curved run-up wall in 1.8, 2.4 and 3.0 m versions with handholds at the top." },
      { title: "Monkey bars and lache bars", desc: "Bar spacing and height matched to age, with full landing mats underneath." },
      { title: "Balance beams and spinners", desc: "Low spinning logs and narrow beams that are fun to fail safely." },
      { title: "Timing system", desc: "Start pad, finish buzzer and leaderboard screen for timed runs and competitions." },
    ],
    gallery: [
      { src: projectImages.ninjaProject, alt: "Indoor kids ninja course with rings and warped wall", caption: "Senior lane with rings and warped wall." },
      { src: productImages.ninjaCourse, alt: "Modular ninja obstacles on padded landing mats", caption: "Modular obstacles on full landing mats." },
      { src: projectImages.fecCenter, alt: "Family entertainment centre with ninja zone next to soft play", caption: "Ninja zone beside the soft play area." },
    ],
    specTable: {
      heading: "Kids Ninja Course Specification by Age Band",
      intro: "Planning values for an indoor kids course. Final heights follow the applicable standard and the operator's risk assessment.",
      caption: "Kids ninja warrior obstacles, heights and landing surfaces by age band",
      columns: ["Age band", "Sample obstacles", "Max hand height", "Warped wall", "Landing mat"],
      rows: [
        ["4–6", "Steps, low nets, short bars", "≈ 1.5 m", "Not used / 1.2 m ramp", "Full-coverage foam mats"],
        ["7–9", "Rings, ropes, small wall", "≈ 2.0 m", "1.8 m", "Thick landing mats under hang zones"],
        ["10–12", "Salmon ladder, lache, ledges", "≈ 2.4 m", "2.4–3.0 m", "Crash mats sized to drop height"],
      ],
      footnote: "Values are planning ranges, not certified limits. Separate lanes by age and supervise with trained staff.",
    },
    audienceTitle: "Who Adds a Kids Ninja Course",
    audienceIntro: "A kids ninja lane is one of the fastest ways to raise the age ceiling of an indoor playground.",
    audience: [
      { title: "Indoor playgrounds", desc: "Keep 8–12 year olds who have outgrown soft play." },
      { title: "Trampoline parks", desc: "Add a timed attraction that runs on low staff numbers." },
      { title: "Birthday party venues", desc: "Package heats, medals and a podium photo into party bundles." },
      { title: "Family entertainment centres", desc: "Create a league or membership product with seasonal leaderboards." },
    ],
    related: [
      cluster.trampolineLayout,
      cluster.installation,
      cluster.maintenance,
      cluster.startBusiness,
      { label: "Ninja courses for education centres", href: "/ninja-course-equipment-indoor-education-centers" },
      { label: "Ninja course equipment", href: "/products/ninja-course" },
    ],
    faq: [
      { title: "What age is a kids ninja warrior course for?", desc: "Most kids courses serve ages 4–12, split into junior, intermediate and senior lanes with different heights and obstacles." },
      { title: "How much space does a kids ninja course need?", desc: "About 150–400 m² for one or two lanes, including run-up, landing zones and a viewing area." },
      { title: "Is a ninja course safe for young children?", desc: "Yes, when the lane is sized to age, landing mats cover every fall zone and staff supervise. Juniors use low obstacles with feet close to the mat." },
      { title: "How tall should a kids warped wall be?", desc: "Common sizes are 1.8 m for ages 7–9 and 2.4–3.0 m for ages 10–12. Young children usually use a low ramp instead." },
      { title: "How does a kids ninja course make money?", desc: "Timed-run tickets, birthday party packages, weekly classes and seasonal leagues, often bundled with general admission." },
      { title: "Can obstacles be changed later?", desc: "Yes. Modular frames allow obstacles to be swapped or re-arranged each season." },
      { title: "Does NinescapeLand design kids ninja courses?", desc: "Yes. We provide a free 3D layout with lanes by age band, landing zones and viewing areas." },
    ],
    sources: [sources.astmF1487, sources.en1176, sources.cpsc, sources.hhsGuidelines, sources.astmF2970],
  },

  trampolineLayout: {
    slug: "indoor-trampoline-park-layout-design",
    title: "Indoor Trampoline Park Layout Design",
    metaTitle: "Indoor Trampoline Park Layout Design Guide",
    metaDescription: "Indoor trampoline park layouts for 500, 1,000 and 2,000 m² halls: zone mix, dodgeball, foam pit, slam dunk, guest flow and safety clearances.",
    keywords: ["indoor trampoline park layout design", "trampoline park design", "trampoline park layout", "trampoline park floor plan"],
    kicker: "500 / 1,000 / 2,000 m² · Zone Mix · Guest Flow",
    description: "The same budget can produce a busy park or an empty one depending on the floor plan. This guide shows how to lay out an indoor trampoline park at three common hall sizes: which zones to include, how much area each one takes, how guests move from check-in to court, and the clearances that keep it safe.",
    primaryCta: "Get My Trampoline Park Layout",
    secondaryCta: "See Layouts by Size",
    heroImage: heroImages.trampolinePark,
    heroImageAlt: "3D perspective render of an indoor trampoline park layout with main court, dodgeball and foam pit",
    metrics: [
      { value: "55–65%", label: "Share of floor for jump zones" },
      { value: "≥ 6 m", label: "Clear height for dunk and pit zones" },
      { value: "3", label: "Reference hall sizes" },
      { value: "1 way", label: "Guest flow from check-in to exit" },
    ],
    frameworkTitle: "Five Layout Rules That Decide How a Park Performs",
    frameworkIntro: "These rules apply at every size and matter more than any single attraction.",
    framework: [
      { title: "1. Lead with the main court", desc: "Put the largest free-jump court in view of the entrance. It sells the park and is the easiest zone to supervise." },
      { title: "2. Group by noise and age", desc: "Keep dodgeball and dunk lanes together, and the toddler court away from them near seating." },
      { title: "3. Plan one-way guest flow", desc: "Check-in, sock purchase, safety briefing, lockers, courts, café and exit should follow one loop with no back-tracking." },
      { title: "4. Respect clearances", desc: "Leave padded walkways around courts and full clear height above dunk, pit and high-performance zones." },
      { title: "5. Give parents a view", desc: "A café or seating deck with sightlines to every court raises dwell time and food sales." },
    ],
    equipmentTitle: "Zones to Choose From",
    equipmentIntro: "Not every park needs every zone. Choose by hall size, ceiling height and target age.",
    equipment: [
      { title: "Main free-jump court", desc: "Connected trampoline beds with angled walls; the core of every layout." },
      { title: "Dodgeball court", desc: "Enclosed court with nets; good for groups, parties and leagues." },
      { title: "Foam pit or airbag", desc: "Landing zone for flips and jumps from platforms; needs pit depth or a raised deck." },
      { title: "Slam dunk lane", desc: "Trampoline lanes facing basketball hoops; needs high clear height." },
      { title: "Toddler court", desc: "Smaller, lower-rebound beds for under-6s in a quieter corner." },
      { title: "Add-on attractions", desc: "Ninja lane, climbing wall, battle beam or interactive trampoline games to raise repeat visits." },
    ],
    gallery: [
      { src: projectImages.trampolineProject, alt: "Main trampoline court with angled wall beds", caption: "Main court in view of the entrance." },
      { src: productImages.trampolinePark, alt: "Dodgeball court and foam pit in a trampoline park", caption: "Dodgeball and foam pit grouped together." },
      { src: projectImages.bouncePark, alt: "Indoor bounce park with seating area for parents", caption: "Parent seating with sightlines to the courts." },
    ],
    specTable: {
      heading: "Trampoline Park Zone Mix by Hall Size",
      intro: "Reference layouts. Adjust for columns, ceiling height and local code.",
      caption: "Indoor trampoline park zone allocation at 500, 1,000 and 2,000 m²",
      columns: ["Zone", "500 m² hall", "1,000 m² hall", "2,000 m² hall"],
      rows: [
        ["Main free-jump court", "150–180 m²", "250–300 m²", "450–550 m²"],
        ["Dodgeball", "—", "80–100 m²", "150–200 m²"],
        ["Foam pit / airbag", "40–60 m²", "60–90 m²", "100–150 m²"],
        ["Slam dunk", "—", "40–60 m²", "80–100 m²"],
        ["Toddler court", "30–40 m²", "50–70 m²", "80–120 m²"],
        ["Add-on attractions", "30–50 m²", "100–150 m²", "300–400 m²"],
        ["Check-in, café, lockers, toilets", "150–200 m²", "250–300 m²", "450–550 m²"],
      ],
      footnote: "Areas are planning ranges. Clear height, column grid and exit requirements may change the final split.",
    },
    audienceTitle: "Who This Layout Guide Is For",
    audienceIntro: "Useful before signing a lease, because the hall decides which zones are possible.",
    audience: [
      { title: "Investors comparing halls", desc: "Check whether a building's size and height suit the zones you want." },
      { title: "Existing parks expanding", desc: "Find room for a dodgeball court, toddler area or ninja lane." },
      { title: "FEC developers", desc: "Fit a trampoline zone alongside soft play, arcade or café areas." },
      { title: "Architects and fit-out teams", desc: "Get zone areas and clear heights early in the design." },
    ],
    related: [
      cluster.kidsNinja,
      cluster.installation,
      cluster.startBusiness,
      cluster.maintenance,
      { label: "Trampoline park and ninja course builder", href: "/trampoline-park-and-ninja-course-builder" },
      { label: "Trampoline park safety standards", href: "/safety-standards-for-trampoline-park-equipment" },
    ],
    faq: [
      { title: "How big should an indoor trampoline park be?", desc: "Small parks start around 500 m²; most full-feature parks are 1,000–2,000 m², which allows dodgeball, a foam pit, dunk lanes and a café." },
      { title: "What ceiling height does a trampoline park need?", desc: "About 5 m for basic courts and 6 m or more above dunk lanes, foam pits and high-performance zones." },
      { title: "How much of the floor should be trampolines?", desc: "Roughly 55–65% for jump zones, with the rest for check-in, lockers, café, toilets and circulation." },
      { title: "Where should the foam pit go?", desc: "Near the dodgeball and dunk zones, away from the toddler court, where clear height and pit depth or a raised deck are available." },
      { title: "Do I need a separate toddler area?", desc: "Yes. A lower-rebound toddler court keeps under-6s away from older jumpers and is popular for weekday sessions." },
      { title: "Can the layout be changed later?", desc: "Yes, if the original plan leaves expansion space and modular frames are used." },
      { title: "Does NinescapeLand draw the layout?", desc: "Yes. We provide a free 3D perspective layout from your building drawings before you commit." },
    ],
    sources: [sources.astmF2970, sources.en1176, sources.nfpa101, sources.cpsc, sources.astmF1487],
  },

  startBusiness: {
    slug: "how-to-start-an-indoor-playground-business-2026",
    title: "How to Start an Indoor Playground Business in 2026",
    metaTitle: "How to Start an Indoor Playground Business (2026)",
    metaDescription: "A 12-month launch timeline for an indoor playground business: site, licences, insurance, equipment order, fit-out, hiring and soft opening, step by step.",
    keywords: ["how to start an indoor playground business 2026", "how to start an indoor playground business", "indoor playground startup checklist", "open an indoor play centre"],
    kicker: "12-Month Timeline · Checklists · Launch Steps",
    description: "A business plan tells you whether the numbers work. This guide tells you what to do next, and when. It lays out the twelve months from idea to opening day for an indoor playground, with the tasks, decisions and documents for each stage, so nothing critical — a permit, a deposit, an insurance quote — ends up on the critical path.",
    primaryCta: "Start My Project Plan",
    secondaryCta: "See the 12-Month Timeline",
    heroImage: heroImages.home,
    heroImageAlt: "3D perspective render of a new indoor playground ready for opening day",
    metrics: [
      { value: "9–12 mo", label: "Typical idea-to-opening time" },
      { value: "6", label: "Launch stages with checklists" },
      { value: "8–12 wk", label: "Equipment production and shipping" },
      { value: "2–4 wk", label: "Soft opening before launch" },
    ],
    frameworkTitle: "The Six Stages From Idea to Opening Day",
    frameworkIntro: "Stages overlap, but each one has a decision that unlocks the next.",
    framework: [
      { title: "Months 1–2: Market and concept", desc: "Study local families, competitors and pricing; choose the format — soft play, trampoline, ninja or mixed FEC — and the target age range." },
      { title: "Months 2–4: Site and lease", desc: "Shortlist buildings by size, clear height, parking and zoning. Get a free 3D layout before signing so you know what fits." },
      { title: "Months 3–5: Company, permits and insurance", desc: "Register the business, apply for change-of-use and building permits, and get liability insurance quotes early." },
      { title: "Months 5–8: Equipment order and production", desc: "Approve the final design, pay the deposit and schedule production; prepare the building while equipment is made and shipped." },
      { title: "Months 8–10: Fit-out and installation", desc: "Finish floor, ceiling and services, then install equipment and pass inspections." },
      { title: "Months 10–12: Hiring, marketing and soft opening", desc: "Hire and train staff, open pre-sales and parties, run a soft opening, fix issues, then launch." },
    ],
    equipmentTitle: "Launch Checklist: What You Need Before Opening",
    equipmentIntro: "Use this as a final gate. Each item should be signed off before the grand opening.",
    equipment: [
      { title: "Signed lease and permits", desc: "Change-of-use, building, fire and occupancy approvals in place." },
      { title: "Insurance", desc: "Public liability, property and employer cover active from the soft opening." },
      { title: "Certified equipment", desc: "Test reports and certificates for every structure, filed with the inspector." },
      { title: "Booking and POS system", desc: "Online tickets, waivers, party bookings and memberships ready to sell." },
      { title: "Trained team", desc: "Floor staff trained on supervision, daily checks, first aid and cleaning." },
      { title: "Pre-opening marketing", desc: "Local social media, school and parent groups, launch offers and party pre-sales." },
    ],
    gallery: [
      { src: projectImages.fecCenter, alt: "Newly opened family entertainment centre with mixed attractions", caption: "Mixed-format centre at opening." },
      { src: projectImages.softPlayProject, alt: "Soft play structure in a new indoor playground", caption: "Soft play as the core attraction." },
      { src: projectImages.indoorProject, alt: "Indoor playground with parent seating and café", caption: "Parent café planned from day one." },
    ],
    specTable: {
      heading: "12-Month Indoor Playground Launch Timeline",
      intro: "A planning timeline. Permits and building condition vary by city.",
      caption: "Indoor playground startup tasks, owners and outputs by month",
      columns: ["Months", "Main task", "Key decision", "Output"],
      rows: [
        ["1–2", "Market research and concept", "Format and age range", "Concept brief"],
        ["2–4", "Site search and lease", "Building and lease terms", "Signed lease, 3D layout"],
        ["3–5", "Company, permits, insurance", "Permit route", "Applications filed, quotes"],
        ["5–8", "Equipment design and production", "Final design approval", "Deposit paid, production slot"],
        ["8–10", "Fit-out and installation", "Inspection date", "Installed, inspected site"],
        ["10–12", "Hiring, marketing, soft opening", "Launch date", "Trained team, pre-sales"],
      ],
      footnote: "Run permit applications and equipment production in parallel to keep the timeline near 9–12 months.",
    },
    audienceTitle: "Who This Guide Is For",
    audienceIntro: "Written for people turning a plan into an actual opening.",
    audience: [
      { title: "First-time founders", desc: "A month-by-month list of what to do and what to decide." },
      { title: "Franchise and multi-site investors", desc: "A repeatable launch timeline for each new location." },
      { title: "Property owners", desc: "Understand what an indoor playground tenant needs from the building." },
      { title: "Existing businesses adding play", desc: "Cafés, gyms and malls adding a play area alongside current operations." },
    ],
    related: [
      cluster.trampolineLayout,
      cluster.installation,
      cluster.maintenance,
      cluster.kidsNinja,
      { label: "Indoor playground business plan", href: "/indoor-playground-business-plan" },
      { label: "Custom indoor playground cost", href: "/custom-indoor-playground-cost-free-3d-design" },
    ],
    faq: [
      { title: "How long does it take to start an indoor playground business?", desc: "Most projects take 9–12 months from idea to opening, depending on permits, building condition and equipment lead time." },
      { title: "What is the first step to opening an indoor playground?", desc: "Define the format and target age range, then research local demand and competitors before searching for a building." },
      { title: "When should I order equipment?", desc: "After the lease is signed and the layout is final. Production and shipping usually take 8–12 weeks, so order before fit-out starts." },
      { title: "What permits do I need?", desc: "Typically business registration, change-of-use or zoning, building and fire approvals, and an occupancy certificate. Requirements vary by city." },
      { title: "What insurance does an indoor playground need?", desc: "Public liability is essential; property, employer and business interruption cover are also common. Insurers often ask for equipment certificates." },
      { title: "Should I do a soft opening?", desc: "Yes. Two to four weeks of soft opening lets staff practise and lets you fix flow or booking problems before the main launch." },
      { title: "Does NinescapeLand help new operators?", desc: "Yes. We provide a free 3D layout, certified equipment, installation and opening support for first-time operators." },
    ],
    sources: [sources.sba, sources.nfpa101, sources.astmF1487, sources.astmF1918, sources.cpsc],
  },
};

export type WeeklyAggregationPageB10Key = keyof typeof weeklyAggregationPagesB10;
