import type { StableSolutionPageProps } from "@/pages/StableSolutionPage";
import { heroImages, productImages, projectImages, featureImages } from "@/config/galleryImages";

const sources = {
  cpsc: {
    label: "Public Playground Safety Handbook (CPSC 325)",
    publisher: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/s3fs-public/325.pdf",
    note: "Age separation, supervision, surfacing and equipment-layout guidance.",
  },
  astmF1487: {
    label: "ASTM F1487 — Playground Equipment for Public Use",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1487-21.html",
  },
  astmF1918: {
    label: "ASTM F1918 — Soft Contained Play Equipment",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1918-12r19.html",
  },
  astmF2970: {
    label: "ASTM F2970 — Trampoline Courts",
    publisher: "ASTM International",
    url: "https://www.astm.org/f2970-15.html",
  },
  astmF1292: {
    label: "ASTM F1292 — Impact Attenuation of Surfacing Materials",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1292-22.html",
  },
  en1176: {
    label: "EN 1176 — Playground Equipment and Surfacing",
    publisher: "CEN-CENELEC",
    url: "https://www.cencenelec.eu/",
  },
  iso9001: {
    label: "ISO 9001 — Quality Management Systems",
    publisher: "International Organization for Standardization",
    url: "https://www.iso.org/standard/62085.html",
  },
  cbp: {
    label: "Tips for New Importers and Exporters",
    publisher: "U.S. Customs and Border Protection",
    url: "https://www.cbp.gov/trade/basic-import-export/importer-exporter-tips",
    note: "Duties, customs documentation and importer-of-record responsibilities.",
  },
  sba: {
    label: "Calculate Your Startup Costs",
    publisher: "U.S. Small Business Administration",
    url: "https://www.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs",
    note: "Official guidance for separating one-time and recurring costs in a business plan.",
  },
  ada: {
    label: "2010 ADA Standards for Accessible Design",
    publisher: "U.S. Department of Justice",
    url: "https://www.ada.gov/law-and-regs/design-standards/2010-stds/",
  },
  nfpa101: {
    label: "NFPA 101 — Life Safety Code",
    publisher: "National Fire Protection Association",
    url: "https://www.nfpa.org/codes-and-standards/nfpa-101-standard-development/101",
    note: "Occupancy, egress and travel-distance requirements referenced by most local authorities.",
  },
};

export const weeklyAggregationPagesB8: Record<string, StableSolutionPageProps> = {
  factoryDirect: {
    slug: "indoor-playground-equipment-factory-direct-price",
    title: "Indoor Playground Equipment Factory-Direct Price",
    metaTitle: "Indoor Playground Factory-Direct Price Guide",
    metaDescription: "Understand how factory-direct indoor playground pricing is built, how to verify a real source factory, and which import terms change your landed cost.",
    keywords: ["indoor playground equipment factory direct price", "indoor playground factory", "playground equipment factory direct", "buy playground equipment from factory"],
    kicker: "Factory-Direct Pricing · Source Verification · Landed Cost",
    description: "Factory-direct pricing only saves money when you know what sits inside the quoted number. This page breaks down how a source factory builds its price, how to prove you are buying from the maker rather than a reseller, and which shipping and customs terms decide your final landed cost.",
    primaryCta: "Request a Factory-Direct Quote",
    secondaryCta: "See the Price Breakdown",
    heroImage: productImages.indoorPlayground,
    heroImageAlt: "3D perspective render of a custom indoor playground structure quoted directly by the factory",
    metrics: [
      { value: "5 layers", label: "Materials, labour, tooling, QC and freight" },
      { value: "4 proofs", label: "Documents that confirm a real source factory" },
      { value: "3 terms", label: "EXW, FOB and CIF change the comparison" },
      { value: "1 sheet", label: "Itemised quote you can compare line by line" },
    ],
    frameworkTitle: "How a Source Factory Builds an Indoor Playground Price",
    frameworkIntro: "A single square-metre price hides the parts of the cost that actually vary between suppliers. Ask for the structure below and two quotes become comparable.",
    framework: [
      { title: "1. Material and component cost", desc: "Steel tube gauge, post diameter, plywood grade, foam density, PVC thickness, netting specification and hardware finish. Two quotes can differ 30% on materials alone while showing the same drawing." },
      { title: "2. Fabrication and tooling", desc: "Cutting, welding, powder coating, sewing and assembly labour, plus any mould or custom theming tooling. Custom shapes carry one-time tooling that should appear as a separate line, not be hidden in unit price." },
      { title: "3. Quality control and testing", desc: "In-process inspection, pre-shipment checks and the test reports you intend to rely on. Certification testing costs money; a price that excludes it is not cheaper, it is incomplete." },
      { title: "4. Packing, freight and customs", desc: "Volume drives ocean cost more than weight. Confirm cubic metres, container count, packing method, port of loading, incoterm, destination charges, duty responsibility and who acts as importer of record." },
    ],
    equipmentTitle: "What a Factory-Direct Quote Should Itemise",
    equipmentIntro: "Each item below should carry a quantity, specification and price so that you can remove or adjust scope without renegotiating the whole project.",
    equipment: [
      { title: "Structure and platforms", desc: "Posts, beams, decks, stairs, guard panels and fixings, with tube size, wall thickness and coating stated per item." },
      { title: "Soft play and padding", desc: "Foam density, cover material, thickness and fire-performance data for wrapped posts, padded decks and soft shapes." },
      { title: "Slides and play events", desc: "Slide type, material, entry height, exit zone and any rotating or interactive components listed individually." },
      { title: "Flooring and impact surfacing", desc: "Surfacing type, thickness and the critical-fall-height basis it is supplied against, quoted separately from equipment." },
      { title: "Packing and shipping", desc: "Total cubic metres, container loading plan, crate or carton method, port and incoterm, with destination charges identified." },
      { title: "Installation and documentation", desc: "Assembly drawings, parts list, on-site supervision option, spare-parts pack, warranty terms and the test-report set included." },
    ],
    audienceTitle: "Buyers Who Benefit Most From Buying Direct",
    audienceIntro: "Factory-direct purchasing rewards buyers who can review a specification and manage a delivery window; it is less suitable when a project needs a local single point of accountability for everything.",
    audience: [
      { title: "Multi-site operators", desc: "Repeat volume, standardised modules and reorderable parts make a direct factory relationship far cheaper over several openings." },
      { title: "Developers and general contractors", desc: "Teams already handling permits, flooring and installation can take equipment supply direct and keep site coordination in house." },
      { title: "Regional distributors", desc: "Need OEM pricing, consistent finishes, spare-part availability and documentation they can present to their own customers." },
      { title: "First-time operators with support", desc: "Workable when the factory supplies drawings, installation supervision and a clear parts list; risky if nobody owns on-site assembly." },
    ],
    gallery: [
      { src: projectImages.fecCenter, alt: "Close-up of a factory-built indoor playground platform and padded post", caption: "Tube gauge, coating and padding density are where factory quotes really differ." },
      { src: productImages.softPlay, alt: "Soft play modules produced in-house before container packing", caption: "In-house sewing and foam work keep soft play cost and lead time under one roof." },
      { src: projectImages.indoorProject, alt: "Installed indoor playground structure supplied direct from the factory", caption: "The same drawing can be quoted five different ways — compare specifications, not totals." },
    ],
    specTable: {
      heading: "Factory Direct, Trading Company and Local Dealer",
      intro: "Prices move with scope and responsibility, so compare what each channel actually carries.",
      caption: "Indoor playground purchasing channel comparison",
      columns: ["Channel", "Typical price position", "Who owns specification", "Main risk to manage"],
      rows: [
        ["Source factory", "Lowest equipment cost", "Buyer plus factory engineering", "Buyer coordinates freight and install"],
        ["Trading company", "Equipment plus margin", "Agent interprets the brief", "Actual maker may be unknown"],
        ["Local dealer", "Highest, service included", "Dealer owns full scope", "Limited pricing transparency"],
        ["Marketplace listing", "Unit price only", "Nobody owns the full scope", "Specification and testing unclear"],
      ],
      footnote: "Planning guidance only. Confirm duties, taxes and importer responsibilities for your own country before comparing landed costs.",
    },
    sources: [sources.cbp, sources.astmF1487, sources.astmF1918, sources.iso9001],
    related: [
      { label: "Soft play cost breakdown", href: "/soft-play-equipment-supplier-cost-breakdown" },
      { label: "Manufacturer certification checklist", href: "/custom-playground-manufacturer-certification-checklist" },
      { label: "Custom indoor playground cost", href: "/custom-indoor-playground-cost" },
      { label: "Complete play center solutions", href: "/complete-indoor-play-center-solutions" },
      { label: "Profit margin structure", href: "/commercial-indoor-playground-profit-margin" },
    ],
    faq: [
      { title: "Is factory-direct always cheaper?", desc: "Equipment cost is usually lower, but freight, customs, installation and site work move to your side of the table. Compare landed and installed cost, not the quoted equipment figure alone." },
      { title: "How do I confirm a supplier is the real factory?", desc: "Ask for a business licence showing manufacturing scope, production-line photos or a live video walk-through, test reports issued in the factory's own name, and the address on the packing list matching the production site." },
      { title: "Which incoterm should I ask for?", desc: "Request FOB for a comparable baseline, then ask for CIF or DAP as an option. Comparing an EXW quote with a CIF quote without adjusting for freight makes the wrong supplier look cheaper." },
      { title: "What drives ocean freight cost on play equipment?", desc: "Volume, not weight. Ask for total cubic metres and the container loading plan; smart nesting of slides and soft modules can remove a whole container from the shipment." },
      { title: "Can we order a small first project directly?", desc: "Yes. Many buyers start with one zone or one container to test workmanship, documentation and responsiveness, then scale with a standardised module list." },
      { title: "What documents should arrive with the shipment?", desc: "Packing list matched to crate labels, assembly drawings, parts schedule, applicable test reports, warranty terms and a spare-parts inventory." },
    ],
  },

  profitMargin: {
    slug: "commercial-indoor-playground-profit-margin",
    title: "Commercial Indoor Playground Profit Margin",
    metaTitle: "Commercial Indoor Playground Profit Margin",
    metaDescription: "See how indoor play center revenue splits across admission, memberships, parties, food and retail, and which levers actually move gross margin.",
    keywords: ["commercial indoor playground profit margin", "indoor playground profit margin", "indoor play center revenue", "play center gross margin"],
    kicker: "Revenue Mix · Gross Margin · Capacity Planning",
    description: "Margin in an indoor play center is decided by revenue mix and capacity use, not by ticket price alone. This page maps each revenue stream to its typical margin behaviour and shows which design decisions raise or cap the ceiling before you sign a lease.",
    primaryCta: "Model Your Revenue Mix",
    secondaryCta: "See the Margin Levers",
    heroImage: heroImages.projects,
    heroImageAlt: "3D perspective of a commercial indoor play center planned around revenue zones",
    metrics: [
      { value: "5 streams", label: "Admission, membership, parties, F&B, retail" },
      { value: "Peak hours", label: "Most gross profit comes from limited windows" },
      { value: "Capacity cap", label: "Layout fixes the maximum paid headcount" },
      { value: "Mix shift", label: "The fastest lever that needs no new building" },
    ],
    frameworkTitle: "Where Play Center Gross Margin Is Actually Created",
    frameworkIntro: "Fixed costs barely move with attendance, so every additional paid visitor inside existing hours falls almost entirely to gross profit. The work is filling capacity and lifting spend per visit.",
    framework: [
      { title: "1. Capacity before pricing", desc: "Safe simultaneous occupancy, session length and turnover set the maximum paid visits per day. A layout that cannot rotate groups caps revenue no matter how good marketing becomes." },
      { title: "2. Revenue mix by margin", desc: "Admission and memberships carry almost no unit cost. Parties add labour but lift spend per head sharply. Food and retail carry real cost of goods and need attach-rate discipline, not just a menu." },
      { title: "3. Off-peak conversion", desc: "Weekday mornings, school holidays, toddler sessions, camps and private hire monetise hours that already carry rent and staffing. Off-peak programmes usually beat discounting weekends." },
      { title: "4. Margin protection", desc: "Labour scheduled to footfall, maintenance planned rather than reactive, and replaceable wear parts keep the margin you designed. Unplanned closures remove revenue while every fixed cost continues." },
    ],
    equipmentTitle: "Design Choices That Change the Margin Ceiling",
    equipmentIntro: "Equipment and layout decisions made at design stage either open or close the revenue streams you will rely on for years.",
    equipment: [
      { title: "Multi-age zoning", desc: "Separate toddler, junior and active zones so families with different ages all pay, and so one age group does not block another." },
      { title: "Party rooms with sightlines", desc: "Dedicated, bookable rooms that see the play area sell higher-value packages and free the main floor for general admission." },
      { title: "Café adjacency", desc: "Seating placed where adults can supervise raises dwell time and food attach rate without adding staff." },
      { title: "High-throughput attractions", desc: "Ninja lanes, slides and interactive walls that cycle fast keep queues moving and support paid-session formats." },
      { title: "Programmable floor space", desc: "Modular elements that can be reconfigured let the same space host classes, camps and private hire in off-peak hours." },
      { title: "Serviceable wear parts", desc: "Padding, netting and panels specified as replaceable items keep repairs cheap and avoid closing a zone for weeks." },
    ],
    audienceTitle: "Who Uses a Margin Model Before Committing",
    audienceIntro: "This structure is aimed at people who must defend an investment case rather than estimate a ticket price.",
    audience: [
      { title: "First-time operators", desc: "Need to know which revenue streams must exist on day one and which can be added after opening." },
      { title: "Multi-site operators", desc: "Compare mix performance across venues and standardise the zones that produce the highest contribution." },
      { title: "Investors and lenders", desc: "Look for capacity assumptions, revenue mix and cost structure stated separately, with sensitivity on attendance." },
      { title: "Mall and leisure landlords", desc: "Assess whether a proposed play center can carry its rent from realistic paid capacity rather than optimistic footfall." },
    ],
    gallery: [
      { src: heroImages.home, alt: "Indoor play center main hall designed for high paid capacity", caption: "Circulation and zoning decide how many paying guests the venue can hold safely." },
      { src: projectImages.bouncePark, alt: "Trampoline and active zone used for paid timed sessions", caption: "High-throughput attractions support timed sessions and lift revenue per hour." },
      { src: projectImages.fecCenter, alt: "Soft play zone adjacent to seating and café area", caption: "Café adjacency raises dwell time and food attach rate without extra staffing." },
    ],
    specTable: {
      heading: "Revenue Streams and Their Margin Behaviour",
      intro: "Use this to structure your own model; actual figures depend on local pricing, wages, rent and tax.",
      caption: "Indoor play center revenue stream comparison",
      columns: ["Revenue stream", "Cost of sale", "Margin behaviour", "Main constraint"],
      rows: [
        ["General admission", "Very low", "Highest incremental margin", "Safe capacity and peak hours"],
        ["Memberships", "Very low", "Stabilises off-peak revenue", "Retention and crowding risk"],
        ["Parties and private hire", "Labour and consumables", "High value per booking", "Room count and staffing"],
        ["Food and beverage", "Real cost of goods", "Moderate, depends on attach rate", "Kitchen scope and waste"],
        ["Retail, socks and merchandise", "Stock cost", "Small but reliable add-on", "Inventory and shrinkage"],
      ],
      footnote: "Illustrative planning structure, not a financial projection or investment advice. Build your model on local costs and verified attendance assumptions.",
    },
    sources: [sources.sba, sources.cpsc, sources.astmF1487, sources.nfpa101],
    related: [
      { label: "Indoor playground business plan", href: "/indoor-playground-business-plan" },
      { label: "Total cost of ownership", href: "/indoor-playground-total-cost-of-ownership" },
      { label: "Education combo layout ideas", href: "/kids-education-combo-play-center-layout-ideas" },
      { label: "Factory-direct equipment price", href: "/indoor-playground-equipment-factory-direct-price" },
      { label: "Complete play center solutions", href: "/complete-indoor-play-center-solutions" },
    ],
    faq: [
      { title: "Which revenue stream carries the best margin?", desc: "General admission and memberships, because the marginal cost of one more visitor inside existing hours is close to zero. Parties raise revenue per head but add labour; food and retail carry genuine cost of goods." },
      { title: "Does raising ticket prices raise margin?", desc: "Only until attendance falls. In most venues, filling off-peak hours and lifting spend per visit protects margin better than repeated price increases." },
      { title: "How does equipment choice affect profitability?", desc: "Through capacity, throughput and maintenance. Zones that rotate groups quickly and use replaceable wear parts keep revenue running and repair costs predictable." },
      { title: "What usually destroys a play center's margin?", desc: "Rent set against optimistic attendance, labour not scheduled to footfall, unplanned closures for repairs, and a layout that cannot host off-peak programmes." },
      { title: "Should food service be in the first phase?", desc: "Include seating and adjacency from day one even if the menu starts small. Retrofitting a kitchen or seating area later is far more expensive than reserving the space." },
      { title: "What can a manufacturer contribute to the model?", desc: "We can provide capacity-oriented layouts, zone-by-zone equipment schedules, throughput assumptions, wear-part lists and maintenance intervals for your financial model." },
    ],
  },

  comboLayout: {
    slug: "kids-education-combo-play-center-layout-ideas",
    title: "Kids Education Combo Play Center Layout Ideas",
    metaTitle: "Education Combo Play Center Layout Ideas",
    metaDescription: "Zone a combined education and active play center: learning rooms, movement zones, noise control, age routing and supervision sightlines in one layout.",
    keywords: ["kids education combo play center layout ideas", "indoor playground layout", "education play center zoning", "learning and play center floor plan"],
    kicker: "Zoning · Circulation · Noise Control",
    description: "Combining classes with active play fails when both share one open hall. This page covers how to zone a combined education and play center so quiet learning, loud movement, age routing and staff supervision all work in the same building.",
    primaryCta: "Get a Zoned Layout Concept",
    secondaryCta: "See the Zoning Rules",
    heroImage: heroImages.faq,
    heroImageAlt: "3D perspective of a combined education and active play center with separated zones",
    metrics: [
      { value: "4 zones", label: "Learn, move, regulate and support" },
      { value: "2 routes", label: "Separate class and public circulation" },
      { value: "Acoustics", label: "Noise buffer between loud and quiet use" },
      { value: "Sightlines", label: "One adult can watch each zone" },
    ],
    frameworkTitle: "Zone the Building Before Choosing Equipment",
    frameworkIntro: "In a combo center the floor plan carries the programme. Decide adjacency, noise and routing first; the equipment list then follows without forcing later rebuilds.",
    framework: [
      { title: "1. Group by noise and focus", desc: "Place instruction rooms at one end, active play at the other, and put storage, toilets or a café between them as an acoustic buffer. Never separate a class from a trampoline zone with a single glass wall." },
      { title: "2. Split the circulation", desc: "Class groups need a route from entry to room that does not cross the active floor. Two routes cut disruption, protect scheduled sessions and let general admission keep running." },
      { title: "3. Route by age and ability", desc: "Toddler areas need enclosure and short sightlines; school-age zones need queueing space and exit clearance. Mark transitions clearly so children do not drift into an age band that is unsafe for them." },
      { title: "4. Plan the transition spaces", desc: "Shoes, bags, hand washing, water and waiting are where combined centers break down. Give each a defined location sized for a whole class arriving at once." },
    ],
    equipmentTitle: "Zones a Combined Center Usually Needs",
    equipmentIntro: "A six-zone template that keeps education and active play compatible in one footprint.",
    equipment: [
      { title: "Instruction rooms", desc: "Enclosed, acoustically treated rooms with tables, display wall and a door that does not open onto the active floor." },
      { title: "Active movement zone", desc: "Climbing, slides, ninja lanes or trampolines grouped together with shared impact surfacing and clear queue space." },
      { title: "Toddler enclosure", desc: "A visually contained low-height area with one entry point, soft surfacing and adult seating inside the sightline." },
      { title: "Interactive learning wall", desc: "Projection or panel-based activities that bridge the two halves and can be used by a class or by walk-in visitors." },
      { title: "Calm regulation corner", desc: "A low-stimulation space near the classrooms so a child can reset without leaving supervision." },
      { title: "Support and transition band", desc: "Shoe storage, bag lockers, toilets, water and buggy parking positioned between entry and both zones." },
    ],
    audienceTitle: "Operators Running Classes and Open Play Together",
    audienceIntro: "Anyone selling both scheduled programmes and general admission from one building needs the layout to serve both without conflict.",
    audience: [
      { title: "Education and play combo operators", desc: "Run classes on weekday mornings and open play at weekends from the same floor area." },
      { title: "Early learning centres adding play", desc: "Need an active zone that supports curriculum sessions without disturbing teaching rooms." },
      { title: "Franchise and multi-site brands", desc: "Want a repeatable zoning template that adapts to different unit shapes while keeping the same programme." },
      { title: "Landlords and fit-out teams", desc: "Review acoustics, egress, services and load before approving a mixed-use leisure and education tenant." },
    ],
    gallery: [
      { src: heroImages.projects, alt: "Zoned indoor play center with separated active and quiet areas", caption: "Buffer space between loud and quiet zones protects both programmes." },
      { src: productImages.indoorPlayground, alt: "Multi-level active play structure within a combined center", caption: "Active zones grouped together share surfacing, queueing and supervision." },
      { src: projectImages.softPlayProject, alt: "Toddler soft play enclosure with adult seating in sightline", caption: "Toddler enclosures need one entry point and seating inside the sightline." },
    ],
    specTable: {
      heading: "Zone Adjacency and Noise Planning",
      intro: "Use this as a check before the layout is fixed; local codes govern egress, occupancy and acoustics.",
      caption: "Education combo play center zoning comparison",
      columns: ["Zone", "Noise level", "Good neighbour", "Keep away from"],
      rows: [
        ["Instruction rooms", "Quiet", "Calm corner, support band", "Trampolines, ninja lanes"],
        ["Active movement zone", "Loud", "Café, spectator seating", "Classrooms, sleep or calm rooms"],
        ["Toddler enclosure", "Moderate", "Adult seating, toilets", "Older-child queueing lanes"],
        ["Calm regulation corner", "Very quiet", "Classrooms", "Main entry and event space"],
        ["Café and seating", "Moderate", "Active zone viewing line", "Instruction rooms"],
      ],
      footnote: "Layout guidance only. Occupancy, egress, fire and accessibility requirements must be confirmed with your local authority and design team.",
    },
    sources: [sources.nfpa101, sources.ada, sources.cpsc, sources.astmF1487],
    related: [
      { label: "Educational indoor play area design", href: "/how-to-design-an-educational-indoor-play-area" },
      { label: "Interactive learning play equipment", href: "/interactive-play-equipment-for-learning-centers" },
      { label: "Modular reconfigurable play", href: "/modular-reconfigurable-indoor-play-equipment" },
      { label: "Profit margin structure", href: "/commercial-indoor-playground-profit-margin" },
      { label: "Free 3D play center design", href: "/free-3d-design-for-indoor-play-center" },
    ],
    faq: [
      { title: "How much space should a combo center give to classrooms?", desc: "Size classrooms from your scheduled group size and session count, then allocate the remaining floor to active play. Working the other way around usually produces rooms too small to sell." },
      { title: "How do we stop noise ruining classes?", desc: "Separate the zones physically, use support space as a buffer, treat classroom ceilings and walls, and keep classroom doors off the active floor. Glass alone does not control impact noise." },
      { title: "Can the same equipment serve classes and open play?", desc: "Yes, if it is modular and has a defined bypass route. Reconfigurable elements let one zone host a structured session in the morning and free play in the afternoon." },
      { title: "How many staff does a zoned layout need?", desc: "Design so each zone can be supervised from a single standing position, then confirm staffing against your local supervision requirements and insurer conditions." },
      { title: "Should toddler and school-age zones share surfacing?", desc: "Only where the critical fall height and activity type match. Mixing them usually means over-specifying one zone and under-protecting the other." },
      { title: "What do you need to produce a zoning concept?", desc: "A dimensioned floor plan with ceiling height, column positions, entries and exits, your programme schedule and target group sizes." },
    ],
  },

  trampolineNinjaBuilder: {
    slug: "trampoline-park-and-ninja-course-builder",
    title: "Trampoline Park and Ninja Course Builder",
    metaTitle: "Trampoline Park and Ninja Course Builder",
    metaDescription: "Build a trampoline park and ninja course in one venue: clear height, structural loads, run-out zones, build sequence and combined handover checks.",
    keywords: ["trampoline park and ninja course builder", "trampoline park builder", "combined trampoline and ninja park", "trampoline ninja course construction"],
    kicker: "Combined Build · Clear Height · Handover Checks",
    description: "Trampoline courts and ninja courses compete for the same ceiling height, structural anchorage and run-out space. This page covers building both in one venue: height planning, load paths, buffer zones, installation sequence and the combined inspection you should require at handover.",
    primaryCta: "Plan a Combined Build",
    secondaryCta: "See the Build Sequence",
    heroImage: productImages.trampolinePark,
    heroImageAlt: "3D perspective of a combined trampoline park and ninja course venue",
    metrics: [
      { value: "Clear height", label: "Measured under services, not to slab" },
      { value: "Load paths", label: "Anchorage confirmed before layout is fixed" },
      { value: "Run-out", label: "Buffer zones designed between the two zones" },
      { value: "1 handover", label: "Single inspection covering both standards" },
    ],
    frameworkTitle: "Sequence a Two-Discipline Venue Correctly",
    frameworkIntro: "Most combined-venue problems are decided before manufacturing: available clear height, where loads can be taken, and how the two zones meet. Fix those three and the rest is scheduling.",
    framework: [
      { title: "1. Survey real clear height", desc: "Measure to the lowest obstruction — sprinklers, ducts, lighting, beams — across the whole footprint, not at the highest point. Ninja hanging elements and trampoline jump zones both lose usable height to services." },
      { title: "2. Confirm the structure", desc: "Trampoline frames sit on the floor and load it dynamically; many ninja elements want overhead or wall anchorage. Get slab, wall and roof capacity confirmed by the building engineer before committing to a layout." },
      { title: "3. Design the boundary", desc: "Set landing and run-out space, spectator lines, walkways and padded transitions between the courts and the course so a user exiting one zone never lands in the other." },
      { title: "4. Build in the right order", desc: "Complete surfacing and flooring, then trampoline frames and padding, then ninja structures and anchorage, then netting, signage and final adjustment. Out-of-order installation forces rework on padding and net lines." },
    ],
    equipmentTitle: "Scope a Combined Trampoline and Ninja Build",
    equipmentIntro: "Six delivery blocks that should each appear in the quotation with its own specification and acceptance criteria.",
    equipment: [
      { title: "Trampoline courts", desc: "Main jump grid, wall courts and performance areas with frame, spring or bungee system, pad specification and bed sizing stated." },
      { title: "Landing and foam zones", desc: "Airbags, foam pits or landing mats with tested depth and replacement plan for wear items." },
      { title: "Ninja course structures", desc: "Warped walls, hanging obstacles, rigs and timed lanes with anchorage detail, adjustment range and difficulty grading." },
      { title: "Impact surfacing", desc: "Surfacing supplied against a stated critical fall height for each zone, including walkways and transitions." },
      { title: "Enclosure and netting", desc: "Perimeter netting, dividers, gates and entry control designed so the two zones cannot mix uncontrolled." },
      { title: "Documentation and training", desc: "Layout drawings, load statements, applicable test reports, inspection schedule, operator manual and staff briefing material." },
    ],
    audienceTitle: "Projects That Combine Both Disciplines",
    audienceIntro: "Combined venues suit operators who need weekday and weekend demand from different user groups in one lease.",
    audience: [
      { title: "FEC and trampoline park operators", desc: "Add ninja lanes to lift dwell time and serve older children without another building." },
      { title: "Sports and fitness facilities", desc: "Use ninja and trampoline elements for classes, competitions and conditioning under a defined supervision plan." },
      { title: "Developers converting warehouses", desc: "Need an early answer on clear height and structural capacity before signing a lease." },
      { title: "School and academy projects", desc: "Require graded difficulty, instructor-led rotation and documentation their insurer will accept." },
    ],
    gallery: [
      { src: projectImages.trampolineProject, alt: "Trampoline court design with perimeter padding and netting", caption: "Court layout, padding and net lines are set before ninja anchorage is fixed." },
      { src: featureImages.ninja, alt: "Indoor ninja course obstacles with overhead rig", caption: "Hanging obstacles need confirmed overhead anchorage and adjustment range." },
      { src: projectImages.bouncePark, alt: "Active zone transition between trampoline and obstacle areas", caption: "Transitions and run-out space keep the two disciplines safely separated." },
    ],
    specTable: {
      heading: "Trampoline Zone vs Ninja Zone Requirements",
      intro: "Both zones can share a venue, but their technical demands differ and must be checked separately.",
      caption: "Combined trampoline and ninja venue requirement comparison",
      columns: ["Requirement", "Trampoline courts", "Ninja course", "Combined venue note"],
      rows: [
        ["Clear height driver", "Jump height above bed", "Obstacle and fall clearance", "Design to the tighter of the two"],
        ["Load path", "Dynamic floor loading", "Overhead or wall anchorage", "Engineer must confirm both"],
        ["Surfacing basis", "Pads and landing systems", "Impact surfacing to fall height", "Do not average the two zones"],
        ["Supervision", "Court marshalling", "Lane control and queueing", "Separate staff positions"],
        ["Reference standard", "ASTM F2970 practice", "ASTM F1487 style structures", "Ask which applies to each item"],
      ],
      footnote: "Technical planning guidance only. The applicable standards, permits and inspection regime must be confirmed with your local authority, engineer and insurer.",
    },
    sources: [sources.astmF2970, sources.astmF1487, sources.astmF1292, sources.nfpa101],
    related: [
      { label: "ASTM trampoline park supplier", href: "/astm-certified-commercial-trampoline-park-supplier" },
      { label: "Ninja courses for education centers", href: "/ninja-course-equipment-indoor-education-centers" },
      { label: "ASTM-compliant play structures", href: "/astm-certified-indoor-playground-structures" },
      { label: "Trampoline park FEC solutions", href: "/trampoline-park-fec-solutions" },
      { label: "Complete play center solutions", href: "/complete-indoor-play-center-solutions" },
    ],
    faq: [
      { title: "What clear height does a combined venue need?", desc: "Work from the lowest obstruction across the footprint and the specific elements you intend to install; trampoline jump zones and hanging ninja obstacles each set their own clearance. Send us the survey and we will state the usable height per zone." },
      { title: "Can both zones share the same flooring?", desc: "Walkways can be shared, but impact surfacing must be supplied against each zone's stated critical fall height. Averaging the two usually under-protects the higher-risk area." },
      { title: "Do we need separate supervision for each zone?", desc: "Yes. Court marshalling and lane control are different tasks with different sightlines; plan staff positions for each zone rather than one roaming attendant." },
      { title: "Which should be installed first?", desc: "Surfacing and flooring, then trampoline frames and padding, then ninja structures and anchorage, then netting and final adjustment. Reversing this order forces rework." },
      { title: "How is a combined venue inspected at handover?", desc: "Require zone-by-zone acceptance: anchorage and torque checks, pad coverage, net tension, fall-height confirmation, gate operation and a signed defect list before opening." },
      { title: "Can a combined venue be phased?", desc: "Yes, if anchorage points, surfacing edges and circulation for phase two are engineered into phase one. Retrofitting overhead anchorage afterwards is the expensive path." },
    ],
  },

  softPlayCost: {
    slug: "soft-play-equipment-supplier-cost-breakdown",
    title: "Soft Play Equipment Supplier Cost Breakdown",
    metaTitle: "Soft Play Equipment Cost Breakdown",
    metaDescription: "A line-by-line soft play cost breakdown: structure, padding, slides, ball pit, surfacing, freight and installation, plus a quote-checking method.",
    keywords: ["soft play equipment supplier cost", "soft play equipment cost", "soft play quote breakdown", "soft play equipment price list"],
    kicker: "Itemised Quotes · Like-for-Like Comparison · Scope Control",
    description: "Soft play quotes are hard to compare because suppliers group different things into one number. This page gives the line items a soft play quote should contain, the specifications that change each line, and a checklist for comparing two suppliers on the same basis.",
    primaryCta: "Request an Itemised Soft Play Quote",
    secondaryCta: "See the Line Items",
    heroImage: productImages.softPlay,
    heroImageAlt: "3D perspective of a custom soft play structure priced item by item",
    metrics: [
      { value: "8 lines", label: "Items every soft play quote should show" },
      { value: "3 specs", label: "Foam density, cover grade, frame gauge" },
      { value: "1 basis", label: "Compare suppliers on one scope" },
      { value: "Wear parts", label: "Priced up front, not after year one" },
    ],
    frameworkTitle: "Make Two Soft Play Quotes Comparable",
    frameworkIntro: "Price differences usually come from specification and scope, not from supplier goodwill. Normalise both before deciding anything.",
    framework: [
      { title: "1. Fix the scope first", desc: "Issue the same footprint, ceiling height, age groups, capacity target and required zones to every supplier. Quotes built on different assumptions can never be compared fairly." },
      { title: "2. Require an itemised price", desc: "Ask for quantity, specification and price per line: structure, padding, slides, ball pit, interactive elements, surfacing, freight, installation and spares. A single lump sum hides where the money goes." },
      { title: "3. Compare the specification", desc: "Foam density, cover material grade and thickness, steel tube diameter and wall thickness, netting type, coating and fire-performance data. These drive both cost and service life." },
      { title: "4. Add the full-life items", desc: "Include wear parts, cleaning demands, spare padding, warranty boundaries and lead time. The cheapest structure is not cheapest if covers need replacing in year two." },
    ],
    equipmentTitle: "Line Items in a Complete Soft Play Quote",
    equipmentIntro: "Each line should be separately priced so you can adjust scope without reopening the whole quotation.",
    equipment: [
      { title: "Steel structure and platforms", desc: "Posts, beams, decks, stairs and fixings with tube diameter, wall thickness and coating stated per item." },
      { title: "Padding and soft covering", desc: "Post wraps, deck padding and soft shapes quoted with foam density, cover material, thickness and fire data." },
      { title: "Slides and tubes", desc: "Slide type, material, height, exit-zone requirement and any special sections such as spiral or wave." },
      { title: "Ball pit and fill", desc: "Pit structure, wall height, ball count, ball quality and the cleaning or restocking allowance." },
      { title: "Netting and enclosure", desc: "Perimeter nets, tunnels, climbing nets and mesh with fixing method and tension detail." },
      { title: "Surfacing, freight and installation", desc: "Impact surfacing against a stated fall height, cubic metres and container plan, installation scope, supervision option and spare-parts pack." },
    ],
    audienceTitle: "Buyers Comparing Soft Play Suppliers",
    audienceIntro: "This breakdown is for teams that must justify a purchase decision to someone else.",
    audience: [
      { title: "Play centre operators", desc: "Need a defensible comparison of two or three quotes before committing a large share of the fit-out budget." },
      { title: "Schools and nurseries", desc: "Must show purchasing that scope, safety basis and maintenance responsibility are all accounted for." },
      { title: "Shopping centre and hotel projects", desc: "Compare supplier scope against landlord requirements, cleaning regimes and installation windows." },
      { title: "Distributors and contractors", desc: "Need itemised OEM pricing they can rebuild into their own proposals without hidden gaps." },
    ],
    gallery: [
      { src: projectImages.softPlayProject, alt: "Soft play module showing padded post and cover material", caption: "Foam density and cover grade change both price and service life." },
      { src: productImages.indoorPlayground, alt: "Multi-level soft play structure with slides and netting", caption: "Structure, slides and netting should each carry their own price line." },
      { src: projectImages.fecCenter, alt: "Ball pit and soft play detail in a commercial play centre", caption: "Ball count, ball quality and restocking belong in the quote, not in year one surprises." },
    ],
    specTable: {
      heading: "What Moves Each Soft Play Cost Line",
      intro: "Use this to interrogate a quote; actual prices depend on design, volume, materials market and destination.",
      caption: "Soft play cost line comparison",
      columns: ["Cost line", "Main cost driver", "Spec to confirm", "Common gap in quotes"],
      rows: [
        ["Steel structure", "Height, levels, span", "Tube diameter, wall thickness, coating", "Coating type left unstated"],
        ["Padding and covers", "Surface area", "Foam density, cover grade, fire data", "Fire documentation missing"],
        ["Slides", "Height and type", "Material, exit-zone clearance", "Exit zone not allowed for"],
        ["Ball pit", "Volume and ball count", "Ball quality, restocking plan", "Ball quantity excluded"],
        ["Surfacing", "Critical fall height", "Tested thickness and system", "Priced as optional extra"],
        ["Freight and install", "Cubic metres, site access", "Incoterm, install scope", "Destination charges omitted"],
      ],
      footnote: "Cost-structure guidance only, not a price list. Request a project-specific itemised quotation for your own footprint and destination.",
    },
    sources: [sources.astmF1918, sources.astmF1292, sources.cpsc, sources.cbp],
    related: [
      { label: "Factory-direct equipment price", href: "/indoor-playground-equipment-factory-direct-price" },
      { label: "Custom soft play for schools", href: "/custom-soft-play-equipment-manufacturer-for-schools" },
      { label: "Custom indoor playground cost", href: "/custom-indoor-playground-cost" },
      { label: "Total cost of ownership", href: "/indoor-playground-total-cost-of-ownership" },
      { label: "Manufacturer certification checklist", href: "/custom-playground-manufacturer-certification-checklist" },
    ],
    faq: [
      { title: "Why do soft play quotes differ so much?", desc: "Usually because of specification and scope: steel gauge, foam density, cover grade, whether surfacing and freight are included, and whether installation is priced. Normalise the scope and the gap narrows sharply." },
      { title: "What should never be excluded from a quote?", desc: "Impact surfacing basis, freight volume and terms, installation scope, spare parts, and the test documentation you intend to rely on for inspection or insurance." },
      { title: "How do I compare price per square metre?", desc: "Only within the same specification and height. A single-level toddler zone and a three-level structure with slides are not comparable on area alone." },
      { title: "Which specifications affect long-term cost most?", desc: "Foam density and cover material determine how soon padding needs replacing; coating quality determines corrosion resistance; ball quality determines restocking frequency." },
      { title: "Are wear parts worth pricing up front?", desc: "Yes. Ask for unit prices on padding, covers, netting and ball top-up at the time of purchase so future budgets are predictable and parts remain compatible." },
      { title: "What do you need to issue an itemised quote?", desc: "Footprint dimensions, clear height, age groups, capacity target, destination port or address, and whether you need surfacing and installation included." },
    ],
  },

  certificationChecklist: {
    slug: "custom-playground-manufacturer-certification-checklist",
    title: "Custom Playground Manufacturer Certification Checklist",
    metaTitle: "Playground Manufacturer Certification Check",
    metaDescription: "Audit a custom playground manufacturer: which certificates to request, how to verify test reports, factory audit points and batch traceability.",
    keywords: ["custom indoor playground equipment manufacturer", "playground manufacturer certification", "playground supplier audit checklist", "astm tuv certified playground manufacturer"],
    kicker: "Supplier Audit · Document Verification · Traceability",
    description: "A certificate logo on a website is not evidence. This page is the buyer-side checklist for qualifying a custom playground manufacturer: which documents to request, how to check that a test report covers your product, what to audit in the factory and how batch traceability should work.",
    primaryCta: "Request Our Document Pack",
    secondaryCta: "See the Audit Checklist",
    heroImage: heroImages.aboutUs,
    heroImageAlt: "3D perspective of custom playground equipment produced under an audited quality system",
    metrics: [
      { value: "4 document sets", label: "Company, product, system and batch" },
      { value: "Scope check", label: "Report must match your actual product" },
      { value: "Factory audit", label: "Process controls, not just samples" },
      { value: "Traceability", label: "Batch records linked to your order" },
    ],
    frameworkTitle: "Qualify a Manufacturer in Four Documented Steps",
    frameworkIntro: "The goal is not to collect certificates; it is to confirm that the items you receive were made under the conditions the documents describe.",
    framework: [
      { title: "1. Verify the company", desc: "Business licence showing manufacturing scope, factory address, years in production, export records and whether the entity issuing the quote is the entity that manufactures." },
      { title: "2. Check product test reports", desc: "Read the scope page, not the logo. Confirm the report covers the product family, the standard edition, the tested components and a date range relevant to your order — and that it was issued to this factory." },
      { title: "3. Audit the quality system", desc: "Quality management certification, incoming material inspection, welding and coating controls, in-process checks, pre-shipment inspection records and how non-conforming parts are handled." },
      { title: "4. Require traceability", desc: "Ask how steel batches, foam lots and fabric rolls are recorded against your order, and how a replacement part five years later will match the original specification." },
    ],
    equipmentTitle: "Documents to Request Before Award",
    equipmentIntro: "Ask for these as a single pack; a supplier that can assemble it quickly usually has real systems behind it.",
    equipment: [
      { title: "Company and scope evidence", desc: "Business licence with manufacturing scope, factory photos or video walk-through, and production capacity statement." },
      { title: "Product test reports", desc: "Reports against the standards relevant to your equipment types, with scope, edition and issue date readable." },
      { title: "Quality system certification", desc: "Quality management certificate plus a description of in-process inspection points and records retained." },
      { title: "Material documentation", desc: "Steel grade, coating specification, foam density, fabric performance and fire-behaviour data for the items you are buying." },
      { title: "Inspection and packing records", desc: "Pre-shipment inspection report, packing list matched to crate labels, and photo evidence of finished goods." },
      { title: "After-sales terms", desc: "Warranty scope and exclusions, spare-parts list with prices, lead time for replacements and technical support arrangement." },
    ],
    audienceTitle: "Teams That Must Justify the Supplier Choice",
    audienceIntro: "Qualification documents exist so that procurement, insurance and inspection reviewers can all rely on the same evidence.",
    audience: [
      { title: "Procurement and purchasing", desc: "Need a defensible award file with verified documents rather than marketing claims." },
      { title: "Schools and public buyers", desc: "Must show due diligence on safety documentation and traceability during tender review." },
      { title: "Operators and insurers", desc: "Require documented compliance basis and inspection schedule before the venue opens." },
      { title: "Distributors and importers", desc: "Carry their own liability and need documentation they can pass to end customers and authorities." },
    ],
    gallery: [
      { src: productImages.softPlay, alt: "Soft play components produced under documented material controls", caption: "Material documentation should name foam density, cover grade and fire performance." },
      { src: projectImages.indoorProject, alt: "Finished indoor playground installation with inspection documentation", caption: "Pre-shipment inspection and packing records should match what arrives on site." },
      { src: productImages.trampolinePark, alt: "Trampoline park equipment manufactured under a quality system", caption: "Ask which standard applies to each equipment type, not to the company overall." },
    ],
    specTable: {
      heading: "What Each Certificate Actually Tells You",
      intro: "Different documents answer different questions; none of them replaces the others.",
      caption: "Playground supplier certification comparison",
      columns: ["Document", "What it evidences", "What it does not prove", "How to verify"],
      rows: [
        ["Product test report", "Tested samples met a standard", "Every later batch is identical", "Read scope, edition, issue date, holder"],
        ["Quality system certificate", "Documented process control", "Product-level compliance", "Check certificate number with the issuing body"],
        ["Material data", "Specification of inputs", "Correct assembly or installation", "Match data to the bill of materials"],
        ["Pre-shipment inspection", "Condition of this shipment", "Long-term durability", "Require photos and a signed report"],
        ["Business licence", "Legal entity and scope", "That it owns the factory", "Compare address with packing list"],
      ],
      footnote: "Buyer-side guidance only, not a compliance certification or legal advice. Confirm the standards and approvals required in your own jurisdiction.",
    },
    sources: [sources.astmF1487, sources.astmF1918, sources.en1176, sources.iso9001],
    related: [
      { label: "ASTM-compliant play structures", href: "/astm-certified-indoor-playground-structures" },
      { label: "TUV certified playground supplier", href: "/tuv-certified-playground-equipment-supplier" },
      { label: "Safety certifications", href: "/safety-certifications" },
      { label: "Factory-direct equipment price", href: "/indoor-playground-equipment-factory-direct-price" },
      { label: "Soft play cost breakdown", href: "/soft-play-equipment-supplier-cost-breakdown" },
    ],
    faq: [
      { title: "Is one test report enough for a whole project?", desc: "Rarely. Reports are issued against specific product families and standards, so a trampoline court, a soft play structure and impact surfacing usually need different documents." },
      { title: "How do I know a test report is genuine?", desc: "Check the issuing laboratory, report number, holder name, standard edition and scope, then verify the number directly with the laboratory or certification body." },
      { title: "What should a factory audit look at?", desc: "Incoming material checks, welding and coating process control, in-process inspection records, finished-goods inspection, non-conformance handling and traceability from batch to order." },
      { title: "Does ISO certification mean the product is compliant?", desc: "No. A quality-system certificate evidences process control; product compliance is shown by product testing against the applicable standard." },
      { title: "Why does batch traceability matter after installation?", desc: "Because replacement parts must match the original specification years later. Recorded batches let a supplier reproduce the correct component instead of a near-equivalent." },
      { title: "What can NinescapeLand provide for a tender file?", desc: "Company and scope evidence, applicable test reports, quality-system documentation, material data, inspection records and warranty plus spare-parts terms for your review." },
    ],
  },

  astmStructures: {
    slug: "astm-certified-indoor-playground-structures",
    title: "ASTM-Compliant Indoor Playground Structures",
    metaTitle: "ASTM Indoor Playground Structures Guide",
    metaDescription: "How ASTM requirements apply to indoor playground structures: posts, platforms, barriers, slides, climbers and surfacing, with site acceptance checks.",
    keywords: ["astm certified indoor playground structures", "astm playground standards", "astm f1487 indoor playground", "playground structure compliance"],
    kicker: "Structure Compliance · Component Level · Site Acceptance",
    description: "Compliance is decided component by component, not by a single certificate for the venue. This page explains which structural elements of an indoor playground carry ASTM-referenced requirements, what documentation belongs to each, and how to check them at delivery and on site.",
    primaryCta: "Request Structure Documentation",
    secondaryCta: "See the Component Checks",
    heroImage: productImages.indoorPlayground,
    heroImageAlt: "3D perspective of an indoor playground structure designed to ASTM-referenced requirements",
    metrics: [
      { value: "6 elements", label: "Posts, decks, barriers, slides, climbers, nets" },
      { value: "Fall height", label: "Surfacing matched to each zone" },
      { value: "Entrapment", label: "Openings and gaps checked at handover" },
      { value: "1 file", label: "Documentation kept per structure" },
    ],
    frameworkTitle: "Read Compliance at Component Level",
    frameworkIntro: "Standards describe measurable conditions for parts of a structure. Break the structure into components, assign the requirement to each, then verify at delivery instead of trusting a single logo.",
    framework: [
      { title: "1. Split the structure", desc: "List posts and frames, platforms and decks, guardrails and barriers, access methods, slides, climbing elements, netting and surfacing. Each carries its own dimensional and protective requirements." },
      { title: "2. Assign the requirement", desc: "Ask the manufacturer which standard and edition governs each component and what evidence exists for it. Structural play equipment, soft contained play and surfacing are addressed by different documents." },
      { title: "3. Confirm the fall-height basis", desc: "Every elevated surface has a fall height and the surfacing under it must be supplied against that value. This is the single most common gap between what is quoted and what is installed." },
      { title: "4. Verify on site", desc: "At handover, check barrier heights, opening sizes, protrusions, slide exit zones, surfacing extent, fixing torque and signage, then record the results as the baseline for periodic inspection." },
    ],
    equipmentTitle: "Component-Level Documentation to Keep",
    equipmentIntro: "Hold one file per structure so inspectors, insurers and future maintenance teams all read the same basis.",
    equipment: [
      { title: "Frame and post data", desc: "Tube size, wall thickness, coating, fixing type and torque values, with the as-built layout drawing." },
      { title: "Platform and barrier detail", desc: "Deck heights, guard and barrier arrangement per height band, and the opening dimensions designed to avoid entrapment." },
      { title: "Access and climbing elements", desc: "Stairs, ramps, ladders and climbers with handhold, spacing and clearance detail for the intended age group." },
      { title: "Slide documentation", desc: "Entry, chute, exit height and required exit-zone clearance, plus material and surface-temperature considerations for indoor use." },
      { title: "Netting and enclosure", desc: "Mesh dimensions, tension method and fixing detail for contained play and perimeter enclosures." },
      { title: "Surfacing evidence", desc: "The tested system, thickness and critical fall height it is supplied against, plus the required extent around each element." },
    ],
    audienceTitle: "Who Needs This at Component Level",
    audienceIntro: "Anyone who has to prove, not assert, that a structure was built and installed to a defined basis.",
    audience: [
      { title: "Operators and facility managers", desc: "Need a documented baseline for daily, monthly and annual inspection routines." },
      { title: "Schools and public sector buyers", desc: "Must show reviewers which standard applies to each element of the structure they purchased." },
      { title: "Architects and fit-out teams", desc: "Coordinate fall zones, ceiling clearance, egress and surfacing extent with the equipment layout." },
      { title: "Inspectors and insurers", desc: "Assess whether installed conditions match the supplied documentation and layout drawings." },
    ],
    gallery: [
      { src: projectImages.indoorProject, alt: "Indoor playground platform with guard barriers and padded posts", caption: "Barrier arrangement is set by deck height and intended age group." },
      { src: projectImages.fecCenter, alt: "Climbing and access elements within an indoor play structure", caption: "Access methods and climbers carry their own clearance requirements." },
      { src: productImages.softPlay, alt: "Soft contained play elements with netting and padding", caption: "Soft contained play and structural equipment are covered by different documents." },
    ],
    specTable: {
      heading: "Component, Requirement Focus and Site Check",
      intro: "A practical map from component to verification; always confirm the current standard edition with your supplier and inspector.",
      caption: "Indoor playground structure compliance comparison",
      columns: ["Component", "Requirement focus", "Document to hold", "Site check at handover"],
      rows: [
        ["Posts and frames", "Structural integrity, finish", "Material and coating data", "Fixing torque and coating condition"],
        ["Platforms and barriers", "Height-band protection", "Layout with deck heights", "Barrier height and opening sizes"],
        ["Slides", "Entry, exit and clearance", "Slide specification sheet", "Exit-zone clearance and surfacing"],
        ["Climbers and access", "Reachability and spacing", "Age-group specification", "Handholds, spacing, clear space"],
        ["Contained soft play", "Enclosure and padding", "Soft play test evidence", "Net tension and padding coverage"],
        ["Surfacing", "Impact attenuation", "Tested fall-height evidence", "Thickness and extent under each element"],
      ],
      footnote: "Educational summary only, not a compliance certificate or legal advice. Obtain current standard editions and have installations verified by a qualified inspector.",
    },
    sources: [sources.astmF1487, sources.astmF1292, sources.astmF1918, sources.cpsc],
    related: [
      { label: "Manufacturer certification checklist", href: "/custom-playground-manufacturer-certification-checklist" },
      { label: "Trampoline park safety standards", href: "/safety-standards-for-trampoline-park-equipment" },
      { label: "Trampoline and ninja builder", href: "/trampoline-park-and-ninja-course-builder" },
      { label: "Commercial flooring and mats", href: "/commercial-indoor-playground-flooring-and-mats" },
      { label: "Safety certifications", href: "/safety-certifications" },
    ],
    faq: [
      { title: "Can a whole playground be 'ASTM certified'?", desc: "Standards apply to equipment and components, and testing is performed on defined products against a specific standard edition. Ask which document covers each element rather than expecting one certificate for the venue." },
      { title: "Which standard covers indoor structures?", desc: "Public-use playground equipment, soft contained play and impact surfacing are addressed by different ASTM documents; indoor venues often need evidence for more than one. Confirm the applicable set for your equipment mix." },
      { title: "Why is critical fall height so important?", desc: "It links equipment to surfacing. If surfacing is supplied against a lower fall height than the installed deck, the installation is not protected as designed even when both items look correct." },
      { title: "What should be checked at handover?", desc: "Barrier heights, opening and gap dimensions, protrusions, slide exit zones, surfacing type, thickness and extent, fixing torque, net tension and signage — recorded as a written baseline." },
      { title: "How often should a structure be inspected?", desc: "Operate a routine of frequent visual checks, periodic operational checks and an annual detailed inspection, following your supplier's schedule and local requirements." },
      { title: "What documentation does NinescapeLand supply?", desc: "As-built layout drawings, component specifications, material and coating data, applicable test reports, surfacing fall-height evidence, assembly instructions and an inspection schedule." },
    ],
  },
};

export type WeeklyAggregationPageB8Key = keyof typeof weeklyAggregationPagesB8;
