import type { StableSolutionPageProps } from "@/pages/StableSolutionPage";
import { heroImages, productImages, projectImages } from "@/config/galleryImages";

const sources = {
  cpsc: {
    label: "Public Playground Safety Handbook (CPSC 325)",
    publisher: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/s3fs-public/325.pdf",
    note: "Age separation, use zones, surfacing and supervision guidance.",
  },
  astmF1487: {
    label: "ASTM F1487 — Playground Equipment for Public Use",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1487-21.html",
  },
  astmF1918: {
    label: "ASTM F1918 — Soft Contained Play Equipment",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1918-12r19.html",
  },
  astmF2373: {
    label: "ASTM F2373 — Public Use Play Equipment for Children 6 Months through 23 Months",
    publisher: "ASTM International",
    url: "https://www.astm.org/f2373-11r21.html",
  },
  astmF2970: {
    label: "ASTM F2970 — Trampoline Courts",
    publisher: "ASTM International",
    url: "https://www.astm.org/f2970-15.html",
  },
  en1176: {
    label: "EN 1176 — Playground Equipment and Surfacing",
    publisher: "CEN-CENELEC",
    url: "https://www.cencenelec.eu/",
  },
  cdcMilestones: {
    label: "CDC's Developmental Milestones",
    publisher: "U.S. Centers for Disease Control and Prevention",
    url: "https://www.cdc.gov/ncbddd/actearly/milestones/index.html",
    note: "Movement and physical-development milestones by age.",
  },
  hhsGuidelines: {
    label: "Physical Activity Guidelines for Americans, 2nd Edition",
    publisher: "U.S. Department of Health and Human Services",
    url: "https://health.gov/our-work/nutrition-physical-activity/physical-activity-guidelines",
    note: "Daily activity recommendations for preschool and school-age children.",
  },
  who: {
    label: "Guidelines on Physical Activity, Sedentary Behaviour and Sleep for Children under 5",
    publisher: "World Health Organization",
    url: "https://www.who.int/publications/i/item/9789241550536",
  },
  ada: {
    label: "2010 ADA Standards for Accessible Design",
    publisher: "U.S. Department of Justice",
    url: "https://www.ada.gov/law-and-regs/design-standards/2010-stds/",
  },
};

const cluster = {
  grossMotor: { label: "Gross motor equipment for preschoolers", href: "/gross-motor-play-equipment-for-preschoolers" },
  homeschoolGym: { label: "Homeschool gym programmes", href: "/homeschool-gym-indoor-play-facility" },
  sensorySystem: { label: "Sensory equipment by sensory system", href: "/sensory-playground-equipment-by-sensory-system" },
  curriculum: { label: "Active play curriculum", href: "/active-play-curriculum-for-indoor-play-centers" },
};

export const weeklyAggregationPagesB9: Record<string, StableSolutionPageProps> = {
  grossMotor: {
    slug: "gross-motor-play-equipment-for-preschoolers",
    title: "Gross Motor Play Equipment for Preschoolers",
    metaTitle: "Gross Motor Play Equipment for Preschoolers",
    metaDescription: "Match each preschool gross motor skill — balance, climbing, jumping, crawling, throwing — to the indoor play equipment, heights and zones that build it.",
    keywords: ["gross motor play equipment for preschoolers", "gross motor activities for preschoolers", "preschool gross motor equipment", "indoor gross motor play"],
    kicker: "Ages 2–5 · Skill-to-Equipment Matrix · Indoor Gross Motor Zones",
    description: "Preschool movement is not one skill. Balance, climbing, jumping, crawling and object control each develop on a different timeline and need different equipment, heights and surfacing. This guide maps every gross motor skill to the indoor play pieces that train it, so a preschool, nursery or play centre buys equipment by outcome instead of by catalogue page.",
    primaryCta: "Get a Gross Motor Zone Layout",
    secondaryCta: "See the Skill Matrix",
    heroImage: productImages.softPlay,
    heroImageAlt: "3D perspective render of a preschool soft play gross motor zone with balance beams, ramps and climbing steps",
    metrics: [
      { value: "6 skills", label: "Core gross motor skill groups mapped" },
      { value: "2–5 yrs", label: "Age range covered by the matrix" },
      { value: "≤ 0.8 m", label: "Typical preschool fall height target" },
      { value: "60 min", label: "Daily active play recommended for ages 3–5" },
    ],
    frameworkTitle: "The Six Gross Motor Skill Groups and What Builds Them",
    frameworkIntro: "Each skill group needs a specific type of challenge. If one is missing from the room, children practise the others twice as much and the gap shows up in assessments.",
    framework: [
      { title: "1. Static and dynamic balance", desc: "Low soft beams, stepping pods and wobble bridges. Start with wide surfaces at floor level and narrow them as children progress; dynamic balance needs a moving surface." },
      { title: "2. Climbing and pulling", desc: "Foam step blocks, inclined climbing walls with large holds, cargo nets at low angles. Climbing builds grip, shoulder strength and motor planning." },
      { title: "3. Jumping and landing", desc: "Low platforms of 20–40 cm onto thick mats, plus a toddler bounce pad. Children learn two-foot take-off and controlled landing before hopping on one foot." },
      { title: "4. Crawling and core control", desc: "Tunnels, crawl-through tubes and soft ramps. Crawling remains valuable for bilateral coordination well beyond infancy." },
      { title: "5. Locomotor patterns", desc: "Open running loops, hopscotch-style floor graphics and gallop lanes. These need floor space more than equipment." },
      { title: "6. Object control", desc: "Ball pits, soft throwing targets and rolling ramps. Object control is often the forgotten skill in indoor rooms built only for climbing." },
    ],
    equipmentTitle: "Indoor Equipment Mix for a Preschool Gross Motor Room",
    equipmentIntro: "These pieces form the base of a 40–120 m² gross motor zone. Quantities scale with room size and group size.",
    equipment: [
      { title: "Soft play balance set", desc: "Modular foam beams, arcs and stepping pods in varied widths, covered in wipe-clean PVC for daily sanitising." },
      { title: "Low climbing structure", desc: "Two-level soft-contained structure with ramps, nets and a short slide, built to soft contained play requirements." },
      { title: "Jump-and-land station", desc: "Stepped platforms with crash mats sized for each drop height; optional low-rebound toddler trampoline bed." },
      { title: "Crawl tunnel network", desc: "Tunnels with viewing windows so staff can supervise from outside the structure." },
      { title: "Ball and target zone", desc: "Shallow ball pit with throwing targets and roll-down channels for object-control practice." },
      { title: "Impact-rated floor", desc: "Foam-backed flooring matched to the highest fall height in the room, with matching colours to mark activity zones." },
    ],
    gallery: [
      { src: projectImages.softPlayProject, alt: "Soft play balance and climbing modules for preschool gross motor practice", caption: "Balance beams and climbing steps at preschool scale." },
      { src: projectImages.indoorProject, alt: "Indoor play structure with crawl tunnels and low slides", caption: "Crawl tunnels with supervision windows." },
      { src: projectImages.fecCenter, alt: "Colourful indoor play zone with ball pit and targets", caption: "Object-control zone with ball pit and targets." },
    ],
    specTable: {
      heading: "Gross Motor Skill-to-Equipment Matrix",
      intro: "Use this matrix to check that every skill group has at least one piece of equipment in the room.",
      caption: "Preschool gross motor skills mapped to indoor equipment, age and fall height",
      columns: ["Skill group", "Equipment", "Best age", "Typical height", "Floor area"],
      rows: [
        ["Balance", "Soft beams, stepping pods, wobble bridge", "2–5", "0–30 cm", "8–15 m²"],
        ["Climbing", "Foam steps, inclined wall, low net", "3–5", "40–80 cm", "10–20 m²"],
        ["Jumping", "Stepped platforms, toddler bounce pad", "3–5", "20–40 cm", "8–12 m²"],
        ["Crawling", "Tunnels, crawl tubes, soft ramps", "2–4", "0–60 cm", "6–12 m²"],
        ["Locomotor", "Open loop, floor graphics", "2–5", "Floor", "15–30 m²"],
        ["Object control", "Ball pit, targets, roll ramps", "2–5", "0–40 cm", "6–10 m²"],
      ],
      footnote: "Heights and areas are planning ranges. Final values depend on the applicable standard, room size and group size.",
    },
    audienceTitle: "Who Uses a Gross Motor Room Plan",
    audienceIntro: "The matrix works for any operator who needs to show parents or inspectors that movement is planned, not improvised.",
    audience: [
      { title: "Preschools and nurseries", desc: "Replace a single climbing frame with a balanced room that covers every skill group in the curriculum." },
      { title: "Indoor play centres with a toddler zone", desc: "Turn the under-5 area into a selling point for weekday parent-and-toddler sessions." },
      { title: "Early learning chains", desc: "Standardise one gross motor kit across sites so outcomes and maintenance are consistent." },
      { title: "Paediatric therapy clinics", desc: "Use the same modular pieces for both group play and targeted movement sessions." },
    ],
    related: [
      cluster.homeschoolGym,
      cluster.sensorySystem,
      cluster.curriculum,
      { label: "Early childhood centre equipment", href: "/indoor-playground-equipment-for-early-childhood-centers" },
      { label: "Daycare playground equipment", href: "/daycare-indoor-playground-equipment" },
      { label: "Soft play equipment", href: "/products/soft-play" },
    ],
    faq: [
      { title: "What is gross motor play equipment?", desc: "Equipment that trains large-muscle movements — balance, climbing, jumping, crawling, running and throwing — rather than fine motor skills like gripping a pencil." },
      { title: "How much active play do preschoolers need?", desc: "Public health guidance recommends children aged 3–5 be physically active throughout the day, with at least 60 minutes of moderate-to-vigorous activity for many guidelines. Indoor zones help on bad-weather days." },
      { title: "What fall height is suitable for preschoolers?", desc: "Most preschool gross motor pieces keep fall heights low, typically below about 0.8 m, with impact-rated surfacing matched to the highest point. Confirm against the standard for your market." },
      { title: "How big should a preschool gross motor room be?", desc: "A practical range is 40–120 m², depending on group size. Open floor for running matters as much as equipment footprint." },
      { title: "Can soft play cover all gross motor skills?", desc: "Soft play covers balance, climbing, crawling and jumping well. Add open floor for locomotor patterns and a ball area for object control." },
      { title: "Is the equipment easy to clean?", desc: "Yes. Foam modules use wipe-clean PVC covers and the frames are powder-coated steel, suitable for daily sanitising routines." },
      { title: "Does NinescapeLand design the layout?", desc: "Yes. We provide a free 3D perspective layout that places every skill group, use zone and surfacing area before production." },
    ],
    sources: [sources.cdcMilestones, sources.who, sources.astmF1918, sources.astmF2373, sources.cpsc],
  },

  homeschoolGym: {
    slug: "homeschool-gym-indoor-play-facility",
    title: "Homeschool Gym Programmes for Indoor Play Facilities",
    metaTitle: "Homeschool Gym Programmes for Indoor Play Venues",
    metaDescription: "Turn quiet weekday mornings into homeschool PE revenue: class formats, pricing models, staffing and the indoor equipment a homeschool gym needs.",
    keywords: ["homeschool gym", "homeschool PE classes", "homeschool physical education", "homeschool gym class indoor playground"],
    kicker: "Weekday Revenue · Homeschool PE · Class Formats",
    description: "Most indoor play centres sit half empty from 9 am to 2 pm on school days. Homeschool families are looking for exactly that time slot: structured PE, group games and peer contact in a safe indoor space. This page explains how an indoor playground, trampoline park or ninja venue can run a homeschool gym programme — class formats, pricing, staffing and the equipment that makes it work.",
    primaryCta: "Plan a Homeschool Gym Zone",
    secondaryCta: "See Class Formats",
    heroImage: productImages.ninjaCourse,
    heroImageAlt: "3D perspective render of an indoor ninja course and play hall used for homeschool gym classes",
    metrics: [
      { value: "9–2", label: "Weekday hours most venues leave idle" },
      { value: "4 formats", label: "Class models that fit homeschool groups" },
      { value: "1:10", label: "Typical coach-to-child ratio for ages 6–12" },
      { value: "6–8 wks", label: "Common term length for enrolment" },
    ],
    frameworkTitle: "Four Homeschool Gym Class Formats",
    frameworkIntro: "Homeschool families want predictability and progress. Pick one or two formats and run them on a fixed weekly timetable.",
    framework: [
      { title: "1. Weekly PE term", desc: "A 60-minute class, same time each week, for a 6–8 week term. Warm-up, skill station, team game and cool-down. Sold as a term package." },
      { title: "2. Mixed-age family session", desc: "Siblings of different ages in one slot, with zones split by age. Solves the biggest homeschool scheduling problem: one parent, several children." },
      { title: "3. Skill track", desc: "Ninja, trampoline or parkour progression with badges or levels. Strong retention because children see measurable progress." },
      { title: "4. Co-op hire", desc: "A homeschool co-op books the venue for a private morning and brings its own parents as helpers; the venue supplies one coach and the equipment." },
    ],
    equipmentTitle: "Equipment That Makes a Homeschool Gym Work",
    equipmentIntro: "Classes need stations that a coach can rotate small groups through in 8–10 minutes each.",
    equipment: [
      { title: "Ninja warrior lane", desc: "Modular obstacles — quintuple steps, rings, warped wall — that can be reset to new routes each term." },
      { title: "Trampoline court", desc: "Interconnected beds for jumping drills, dodgeball and controlled skill progressions on an ASTM-referenced court." },
      { title: "Open play floor", desc: "A clear, matted area for team games, relays and warm-ups — the most-used space in a PE class." },
      { title: "Soft play for younger siblings", desc: "A contained toddler zone so parents with under-5s can still attend older children's classes." },
      { title: "Climbing wall", desc: "Low traverse or auto-belay wall for strength, problem solving and turn-taking." },
      { title: "Parent seating with sightlines", desc: "Homeschool parents usually stay; a viewing area with Wi-Fi keeps them coming back." },
    ],
    gallery: [
      { src: projectImages.ninjaProject, alt: "Indoor ninja obstacle lane for structured homeschool PE stations", caption: "Ninja lane reset each term for new routes." },
      { src: projectImages.bouncePark, alt: "Trampoline court with basketball hoops for group games", caption: "Trampoline court for drills and team games." },
      { src: projectImages.softPlayProject, alt: "Soft play zone for younger siblings during classes", caption: "Sibling zone keeps whole families attending." },
    ],
    specTable: {
      heading: "Homeschool Gym Format Comparison",
      intro: "Compare the formats before setting your timetable.",
      caption: "Homeschool gym class formats by group size, duration, pricing and space",
      columns: ["Format", "Group size", "Duration", "Pricing model", "Main space"],
      rows: [
        ["Weekly PE term", "10–20", "60 min", "Term package", "Open floor + stations"],
        ["Mixed-age family session", "15–30", "90 min", "Per family", "Split age zones"],
        ["Skill track", "8–12", "45–60 min", "Monthly membership", "Ninja / trampoline"],
        ["Co-op hire", "20–40", "2–3 hrs", "Flat venue fee", "Whole venue"],
      ],
      footnote: "Ratios and group sizes are planning examples; follow your local supervision rules and insurer requirements.",
    },
    audienceTitle: "Venues That Fit a Homeschool Gym Programme",
    audienceIntro: "Any venue with idle weekday hours and a mix of active zones can add homeschool classes without new building work.",
    audience: [
      { title: "Indoor playground operators", desc: "Fill weekday mornings and build a loyal local customer base that also books parties." },
      { title: "Trampoline parks", desc: "Use courts and dodgeball areas for structured PE rather than open jump only." },
      { title: "Ninja and parkour gyms", desc: "Skill tracks with levels map naturally to term-based homeschool enrolment." },
      { title: "New play centre investors", desc: "Design the floor plan for daytime classes from the start, not as an afterthought." },
    ],
    related: [
      cluster.grossMotor,
      cluster.curriculum,
      cluster.sensorySystem,
      { label: "Homeschool co-op indoor play", href: "/homeschool-coop-indoor-play" },
      { label: "Trampoline park equipment", href: "/products/trampoline-park" },
      { label: "Ninja course equipment", href: "/products/ninja-course" },
    ],
    faq: [
      { title: "What is a homeschool gym?", desc: "A scheduled PE or movement class for homeschooled children, usually held on weekday mornings at a gym, trampoline park, ninja venue or indoor playground." },
      { title: "Why do homeschool families pay for gym classes?", desc: "They want structured physical education, peer contact and a safe indoor space — especially in winter or hot weather — that is hard to provide at home." },
      { title: "When should a play centre run homeschool classes?", desc: "Typically between 9 am and 2 pm on school days, the hours when most venues have the lowest walk-in traffic." },
      { title: "How should homeschool gym classes be priced?", desc: "Common models are term packages, per-family session pricing, monthly memberships for skill tracks and flat fees for co-op private hire." },
      { title: "What equipment is most useful?", desc: "An open play floor, a ninja lane, a trampoline court and a sibling soft play zone. Stations should allow small groups to rotate every 8–10 minutes." },
      { title: "Do parents stay during classes?", desc: "Usually yes. A parent viewing area with clear sightlines improves retention and supervision." },
      { title: "Can NinescapeLand design a venue for daytime classes?", desc: "Yes. We plan zones, sightlines and station flow in a free 3D layout so classes and open play can share the same venue." },
    ],
    sources: [sources.hhsGuidelines, sources.astmF2970, sources.astmF1487, sources.cpsc, sources.ada],
  },

  sensorySystem: {
    slug: "sensory-playground-equipment-by-sensory-system",
    title: "Sensory Playground Equipment by Sensory System",
    metaTitle: "Sensory Playground Equipment by Sensory System",
    metaDescription: "Choose sensory playground equipment by sensory system — vestibular, proprioceptive, tactile, visual and auditory — with specs, use zones and safety notes.",
    keywords: ["sensory playground equipment", "sensory skill development indoor playground equipment", "vestibular play equipment", "proprioceptive play equipment"],
    kicker: "Vestibular · Proprioceptive · Tactile · Visual · Auditory",
    description: "Sensory equipment is easier to specify when you start from the sensory system it stimulates, not from a product name. This catalogue groups indoor sensory playground equipment into five systems, with what each piece does, typical specifications, use-zone needs and the safety points a buyer should confirm before ordering.",
    primaryCta: "Request a Sensory Equipment List",
    secondaryCta: "Browse by System",
    heroImage: projectImages.indoorProject,
    heroImageAlt: "3D perspective render of an indoor sensory play zone with tactile panels, swings and lighting",
    metrics: [
      { value: "5 systems", label: "Sensory systems covered" },
      { value: "20+ items", label: "Equipment types catalogued" },
      { value: "1.8 m", label: "Common minimum use zone around moving items" },
      { value: "3D", label: "Free layout before production" },
    ],
    frameworkTitle: "The Five Sensory Systems in Play Equipment",
    frameworkIntro: "A balanced sensory zone includes calming and alerting input from every system, so children can self-select what they need.",
    framework: [
      { title: "Vestibular (movement and balance)", desc: "Swings, spinners, rocking boats and slides. Provides strong alerting input — needs generous use zones and controlled speed." },
      { title: "Proprioceptive (body awareness)", desc: "Climbing nets, crash pads, resistance tunnels, push-pull panels and jumping. Usually calming and organising." },
      { title: "Tactile (touch)", desc: "Texture walls, ball pits, sand-free sensory tables and soft-fibre panels. Offer a range from smooth to rough." },
      { title: "Visual", desc: "Bubble tubes, light-up floor tiles, mirror panels and dimmable lighting. Include low-stimulation corners as well as bright zones." },
      { title: "Auditory", desc: "Musical panels, chimes and drums placed away from quiet areas; acoustic panels to control overall noise." },
    ],
    equipmentTitle: "Equipment Catalogue by System",
    equipmentIntro: "Typical indoor items and the specification points to request in a quotation.",
    equipment: [
      { title: "Vestibular: platform and nest swings", desc: "Ask for rated load, chain or rope type, swing arc and the required clear zone in front and behind." },
      { title: "Vestibular: low spinners and rockers", desc: "Confirm maximum rotation speed, entrapment gaps and seat height for the target age group." },
      { title: "Proprioceptive: crash pads and climb nets", desc: "Specify foam density, cover material, net mesh size and anchoring method." },
      { title: "Tactile: texture and ball walls", desc: "Request material safety data, cleanability and replacement panel availability." },
      { title: "Visual: bubble tubes and light tiles", desc: "Check low-voltage power, sealed housings, heat output and controllable brightness." },
      { title: "Auditory: musical panels", desc: "Ask for volume range, mounting height and outdoor/indoor rating." },
    ],
    gallery: [
      { src: projectImages.fecCenter, alt: "Colourful tactile and visual sensory panels in an indoor play zone", caption: "Tactile and visual panels at child height." },
      { src: projectImages.softPlayProject, alt: "Soft crash pads and climbing modules for proprioceptive input", caption: "Proprioceptive crash and climb modules." },
      { src: heroImages.faq, alt: "Calm indoor play corner with soft lighting for low-stimulation breaks", caption: "Low-stimulation corner for regulation breaks." },
    ],
    specTable: {
      heading: "Sensory Equipment Comparison by System",
      intro: "Use this table to balance alerting and calming input across the zone.",
      caption: "Sensory playground equipment grouped by sensory system, effect, space and safety focus",
      columns: ["System", "Example equipment", "Typical effect", "Space need", "Key safety check"],
      rows: [
        ["Vestibular", "Nest swing, spinner, rocker", "Alerting", "High (clear zone)", "Use zone, speed, entrapment"],
        ["Proprioceptive", "Crash pad, net, tunnel", "Calming", "Medium", "Fall height, surfacing"],
        ["Tactile", "Texture wall, ball pit", "Variable", "Low", "Material safety, hygiene"],
        ["Visual", "Bubble tube, light tiles", "Alerting or calming", "Low", "Low voltage, sealed housing"],
        ["Auditory", "Musical panels, drums", "Alerting", "Low", "Placement, noise control"],
      ],
      footnote: "Effects are general tendencies; individual children respond differently. Consult a qualified therapist for therapeutic programmes.",
    },
    audienceTitle: "Who Buys Sensory Equipment by System",
    audienceIntro: "Specifying by sensory system makes it easier to justify every item in a budget review.",
    audience: [
      { title: "Special education schools", desc: "Match equipment to individual sensory profiles documented by therapists." },
      { title: "Indoor play centres", desc: "Add a sensory room that attracts families who avoid busy, loud venues." },
      { title: "Therapy and rehab clinics", desc: "Combine vestibular and proprioceptive pieces for targeted sessions." },
      { title: "Libraries and museums", desc: "Create compact sensory corners using tactile, visual and auditory items." },
    ],
    related: [
      cluster.grossMotor,
      cluster.curriculum,
      cluster.homeschoolGym,
      { label: "Designing sensory play areas", href: "/designing-sensory-play-areas-for-education" },
      { label: "Inclusive special education equipment", href: "/inclusive-indoor-play-equipment-special-education" },
      { label: "Sensory inclusive play", href: "/sensory-inclusive-play-equipment" },
    ],
    faq: [
      { title: "What is sensory playground equipment?", desc: "Play equipment designed to stimulate one or more sensory systems — movement, body awareness, touch, sight and sound — to support sensory processing and skill development." },
      { title: "What are the five sensory systems used in play design?", desc: "Vestibular, proprioceptive, tactile, visual and auditory. Some designers also consider interoception, smell and taste." },
      { title: "Which equipment is calming?", desc: "Proprioceptive items such as crash pads, resistance tunnels and heavy-work climbing are generally organising and calming." },
      { title: "Which equipment needs the most space?", desc: "Vestibular items like swings and spinners, because they need clear use zones around their full range of motion." },
      { title: "Are sensory pieces covered by playground standards?", desc: "Structural items fall under public-use playground and soft-contained play standards; electrical items also need electrical safety compliance. Confirm the applicable set per item." },
      { title: "Can a small room include all five systems?", desc: "Yes. A 30–50 m² room can combine wall-mounted tactile, visual and auditory panels with a compact proprioceptive zone and one vestibular item." },
      { title: "Does NinescapeLand customise sensory equipment?", desc: "Yes. Colours, textures, lighting and module sizes are customised, and a free 3D layout is provided before production." },
    ],
    sources: [sources.astmF1487, sources.astmF1918, sources.en1176, sources.cpsc, sources.ada],
  },

  curriculum: {
    slug: "active-play-curriculum-for-indoor-play-centers",
    title: "Active Play Curriculum for Indoor Play Centers",
    metaTitle: "Active Play Curriculum for Indoor Play Centers",
    metaDescription: "Run scheduled movement classes in your indoor play center: curriculum templates for soft play, trampoline and ninja zones, coach ratios and zone planning.",
    keywords: ["active play curriculum", "designing interactive play areas for active learning", "indoor play center classes", "movement class curriculum"],
    kicker: "Class Templates · Coach Ratios · Zone Scheduling",
    description: "Open play brings walk-in traffic; classes bring repeat bookings. An active play curriculum turns the equipment you already have — soft play, trampoline courts and ninja lanes — into structured, age-graded movement classes. This page gives ready-to-adapt lesson templates, staffing ratios and the zoning needed to run classes alongside open play.",
    primaryCta: "Plan Class-Ready Zones",
    secondaryCta: "See Lesson Templates",
    heroImage: productImages.trampolinePark,
    heroImageAlt: "3D perspective render of an indoor trampoline and ninja hall zoned for scheduled movement classes",
    metrics: [
      { value: "3 zones", label: "Soft play, trampoline and ninja templates" },
      { value: "45 min", label: "Standard lesson length" },
      { value: "4 blocks", label: "Warm-up, skill, game, cool-down" },
      { value: "1 timetable", label: "Classes and open play in one venue" },
    ],
    frameworkTitle: "The Four-Block Lesson Structure",
    frameworkIntro: "Every class, whatever the zone, follows the same four blocks so coaches can be trained once and swapped between programmes.",
    framework: [
      { title: "1. Warm-up (5–8 min)", desc: "Locomotor movement and mobility on open floor: jogging, animal walks, dynamic stretches." },
      { title: "2. Skill block (15–20 min)", desc: "One focused skill per week — a landing technique, a ninja obstacle, a balance sequence — taught in small rotating groups." },
      { title: "3. Game block (10–15 min)", desc: "A cooperative or competitive game that applies the skill: relays, tag variants, trampoline dodgeball." },
      { title: "4. Cool-down and review (5 min)", desc: "Calm stretching, a quick skill recap and a badge or progress note for parents." },
    ],
    equipmentTitle: "Curriculum Templates by Zone",
    equipmentIntro: "Each template runs as a 6–8 week term with one new skill per week.",
    equipment: [
      { title: "Soft play: Little Movers (ages 2–4)", desc: "Balance beams, crawl tunnels, ramps and ball pit. Weekly themes: balance, climb, crawl, jump, throw, obstacle story." },
      { title: "Trampoline: Bounce Basics (ages 5–9)", desc: "Safe stance, controlled bounce, stop, seat drop, tuck jump, partner game. Run on dedicated court beds." },
      { title: "Ninja: Obstacle Academy (ages 6–12)", desc: "Grip, swing, balance, wall run, route reading, timed course. Reconfigure modules every term." },
      { title: "Mixed zone: Active Explorers", desc: "Rotate groups across all three zones for a full-venue class, ideal for school trips and homeschool groups." },
      { title: "Zone scheduling", desc: "Block one court or lane per class with soft barriers so open play continues safely in the rest of the venue." },
      { title: "Coach kit", desc: "Cones, markers, soft balls, timers and progress cards stored next to each zone." },
    ],
    gallery: [
      { src: projectImages.trampolineProject, alt: "Trampoline court zoned for a Bounce Basics class", caption: "Dedicated court beds for class use." },
      { src: projectImages.ninjaProject, alt: "Reconfigurable ninja obstacle course for term-based classes", caption: "Ninja modules reset each term." },
      { src: projectImages.softPlayProject, alt: "Soft play modules for toddler movement classes", caption: "Little Movers soft play class zone." },
    ],
    specTable: {
      heading: "Active Play Class Template Comparison",
      intro: "Use this comparison to choose which programmes to launch first.",
      caption: "Indoor play centre class templates by age, ratio, space and equipment",
      columns: ["Programme", "Ages", "Coach ratio", "Space per class", "Core equipment"],
      rows: [
        ["Little Movers", "2–4", "1:6 + parents", "40–60 m²", "Soft play modules"],
        ["Bounce Basics", "5–9", "1:8", "4–6 beds", "Trampoline court"],
        ["Obstacle Academy", "6–12", "1:10", "1 ninja lane", "Ninja modules"],
        ["Active Explorers", "5–12", "1:10", "Whole venue rotation", "All zones"],
      ],
      footnote: "Ratios are planning examples. Follow local supervision rules, insurer requirements and the applicable equipment standards.",
    },
    audienceTitle: "Who Runs an Active Play Curriculum",
    audienceIntro: "Classes suit operators who want predictable weekly revenue on top of open play and parties.",
    audience: [
      { title: "Indoor playground operators", desc: "Launch toddler and kids classes in quiet hours to raise weekday utilisation." },
      { title: "Trampoline park owners", desc: "Add skill-based programmes that build loyalty beyond open jump sessions." },
      { title: "Education and enrichment centres", desc: "Pair academic sessions with movement classes in the same building." },
      { title: "New venue investors", desc: "Design zones with class barriers, coach storage and parent viewing from day one." },
    ],
    related: [
      cluster.grossMotor,
      cluster.homeschoolGym,
      cluster.sensorySystem,
      { label: "How to create an active learning environment", href: "/how-to-create-active-learning-environment" },
      { label: "Education combo layout ideas", href: "/kids-education-combo-play-center-layout-ideas" },
      { label: "Free 3D play center design", href: "/free-3d-design-for-indoor-play-center" },
    ],
    faq: [
      { title: "What is an active play curriculum?", desc: "A structured series of movement classes, organised by age and skill, that runs on a play centre's equipment instead of relying on open play only." },
      { title: "How long should a movement class be?", desc: "About 45 minutes for most ages, split into warm-up, skill block, game and cool-down. Toddler classes are often 30–40 minutes." },
      { title: "Can classes run during open play?", desc: "Yes, if one zone — a court, lane or soft play area — is blocked off with barriers and has its own coach." },
      { title: "What staff ratio is needed?", desc: "Planning examples are about 1:6 for toddlers with parents present, 1:8 on trampolines and 1:10 for ninja classes, subject to local rules and insurance." },
      { title: "Which programme should launch first?", desc: "Usually the one using your most under-used zone in quiet hours — often a toddler soft play class on weekday mornings." },
      { title: "Does equipment need to change for classes?", desc: "Mostly no. Modular ninja obstacles and soft play pieces that can be reconfigured each term keep classes fresh." },
      { title: "Does NinescapeLand help with class-ready layouts?", desc: "Yes. Our free 3D layout includes class zones, barriers, coach storage and parent viewing areas." },
    ],
    sources: [sources.hhsGuidelines, sources.who, sources.astmF2970, sources.astmF1918, sources.cpsc],
  },
};

export type WeeklyAggregationPageB9Key = keyof typeof weeklyAggregationPagesB9;
