import type { StableSolutionPageProps } from "@/pages/StableSolutionPage";
import { heroImages, productImages, projectImages } from "@/config/galleryImages";

const sources = {
  cpsc: {
    label: "Public Playground Safety Handbook (CPSC 325)",
    publisher: "U.S. Consumer Product Safety Commission",
    url: "https://www.cpsc.gov/s3fs-public/325.pdf",
    note: "Age separation, supervision, surfacing and equipment-layout guidance.",
  },
  astmF1487: {
    label: "ASTM F1487 — Playground Equipment for Public Use",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1487-21.html",
  },
  astmF1918: {
    label: "ASTM F1918 — Soft Contained Play Equipment",
    publisher: "ASTM International",
    url: "https://www.astm.org/f1918-12r19.html",
  },
  astmF2970: {
    label: "ASTM F2970 — Trampoline Courts",
    publisher: "ASTM International",
    url: "https://www.astm.org/f2970-15.html",
  },
  ada: {
    label: "2010 ADA Standards for Accessible Design",
    publisher: "U.S. Department of Justice",
    url: "https://www.ada.gov/law-and-regs/design-standards/2010-stds/",
  },
  titleI: {
    label: "Title I, Part A Program",
    publisher: "U.S. Department of Education",
    url: "https://www.ed.gov/grants-and-programs/formula-grants/school-improvement-grants/title-i-part-a-program",
    note: "Official program overview; allowable spending is determined locally and must support the approved school plan.",
  },
  idea: {
    label: "Individuals with Disabilities Education Act",
    publisher: "U.S. Department of Education",
    url: "https://sites.ed.gov/idea/",
  },
  shape: {
    label: "National Standards for K-12 Physical Education",
    publisher: "SHAPE America",
    url: "https://www.shapeamerica.org/standards/pe/",
  },
  grants: {
    label: "Federal Grants Portal",
    publisher: "Grants.gov",
    url: "https://www.grants.gov/",
    note: "Official source for current federal funding opportunities and eligibility rules.",
  },
};

export type WeeklyAggregationPageKey = keyof typeof weeklyAggregationPages;

export const weeklyAggregationPages: Record<string, StableSolutionPageProps> = {
  funding: {
    slug: "how-to-fund-school-playground-equipment",
    title: "How to Fund School Playground Equipment",
    metaTitle: "How to Fund School Playground Equipment",
    metaDescription: "Build a school playground funding plan using grants, district budgets, community partners and phased purchasing, with an approval-ready document checklist.",
    keywords: ["how to fund school playground equipment", "school playground funding", "school playground grants", "playground fundraising plan"],
    kicker: "Funding Guide · District Approval · Phased Procurement",
    description: "A practical funding route for schools that need indoor play equipment but cannot rely on one budget line: define the educational need, match eligible funding, build an approval pack and phase the purchase without losing the safety scope.",
    primaryCta: "Request a Budget-Ready Quote",
    secondaryCta: "Build the Funding Plan",
    heroImage: heroImages.home,
    heroImageAlt: "3D perspective of an indoor school playground planned for phased funding",
    metrics: [
      { value: "4 routes", label: "Budget, grant, partner and fundraising options" },
      { value: "1 brief", label: "Shared scope for every funding application" },
      { value: "3 phases", label: "Core safety, play value and later expansion" },
      { value: "5 files", label: "Approval-ready procurement pack" },
    ],
    frameworkTitle: "Turn a Playground Idea Into a Fundable School Project",
    frameworkIntro: "Funding decisions become easier when the request is tied to a documented student need, a defined user group and a phased scope. Start with the case for the project, not with a catalogue wish list.",
    framework: [
      { title: "1. Define the student outcome", desc: "State who will use the space, when it will be used and which outcome it supports—movement breaks, inclusive access, indoor recess or after-school provision. Keep claims measurable and connected to the school improvement plan." },
      { title: "2. Map eligible funding", desc: "Separate district capital, program budgets, current grants, education foundations and community sponsors. Confirm each source's allowable-use rules before assigning equipment to it; Title I eligibility is never automatic." },
      { title: "3. Create one approval pack", desc: "Use the same floor plan, phased scope, safety basis, total-cost summary and supplier quote for every reviewer. Consistent documents reduce contradictory assumptions between finance, facilities and teaching teams." },
      { title: "4. Phase without redesigning", desc: "Fund surfacing, access and the core structure first; add modular play events later from a pre-engineered expansion plan. This protects circulation and compliance while allowing more than one funding cycle." },
    ],
    equipmentTitle: "Funding Packages Schools Can Approve in Stages",
    equipmentIntro: "Each package protects a complete, usable first phase and leaves documented connection points for later expansion.",
    equipment: [
      { title: "Essential safety package", desc: "Impact surfacing, edge protection, entry control and inspection documentation—the non-negotiable base before optional play features." },
      { title: "Indoor recess starter zone", desc: "Low-height climbers, balance elements and soft modules sized for one supervised class rotation." },
      { title: "Inclusive access package", desc: "Ground-level activities, transfer points, wider circulation and a calm retreat included in the base scope rather than deferred." },
      { title: "Curriculum movement circuit", desc: "Marked routes, climbing, balance and target activities linked to PE or active-learning outcomes." },
      { title: "Community-use expansion", desc: "Durable add-ons and access controls for after-school, weekend or partner-program use." },
      { title: "Future connection kit", desc: "Pre-engineered anchors, electrical allowances and layout reserves that keep a second phase compatible with the first." },
    ],
    audienceTitle: "Teams That Need a Shared Funding Case",
    audienceIntro: "The page is designed for the people who must align educational value, facilities constraints and purchasing rules before a school can issue an order.",
    audience: [
      { title: "School leaders", desc: "Translate a broad wellbeing goal into a defined project with a defensible scope and implementation sequence." },
      { title: "District facilities teams", desc: "Review access, surfacing, installation boundaries and future expansion before approving a site." },
      { title: "PTA and education foundations", desc: "Use a clear phase target and visual concept to communicate exactly what each fundraising milestone unlocks." },
      { title: "Community partners", desc: "Sponsor a named, complete zone with documented use rather than an isolated item that cannot open independently." },
    ],
    gallery: [
      { src: productImages.indoorPlayground, alt: "3D perspective of a phased indoor playground equipment package", caption: "A complete first phase with reserved connections for future expansion." },
      { src: projectImages.softPlayProject, alt: "Durable soft play module suitable for a school starter zone", caption: "Starter equipment selected for supervised class rotation and simple maintenance." },
      { src: projectImages.indoorProject, alt: "Indoor playground project showing clear access and circulation", caption: "Approval drawings should preserve circulation, access and supervision from the first phase." },
    ],
    specTable: {
      heading: "Compare Four School Funding Routes",
      intro: "Confirm current eligibility and local rules before committing costs to any source.",
      caption: "School playground funding route comparison",
      columns: ["Funding route", "Best fit", "Evidence commonly needed", "Planning caution"],
      rows: [
        ["District capital budget", "Permanent facility work", "Site need, cost plan, facilities approval", "Long approval cycle"],
        ["Program or schoolwide funds", "Defined educational outcomes", "Plan alignment and allowable-use review", "Eligibility varies locally"],
        ["Foundation or grant", "Discrete improvement project", "Need statement, beneficiaries, timeline", "Award timing is uncertain"],
        ["PTA / community campaign", "Visible phased package", "Visual concept, target and supplier quote", "Do not omit safety costs"],
      ],
      footnote: "This is project-planning guidance, not funding or legal advice. The school or district must confirm allowable uses and procurement rules.",
    },
    sources: [sources.titleI, sources.grants, sources.cpsc, sources.astmF1487],
    related: [
      { label: "Durable soft play for Title I schools", href: "/durable-soft-play-equipment-title-1-schools" },
      { label: "Custom soft play for schools", href: "/custom-soft-play-equipment-manufacturer-for-schools" },
      { label: "Indoor playground total cost of ownership", href: "/indoor-playground-total-cost-of-ownership" },
      { label: "Free 3D indoor play center design", href: "/free-3d-design-for-indoor-play-center" },
      { label: "After-school program equipment", href: "/after-school-program-indoor-play-equipment" },
    ],
    faq: [
      { title: "Can Title I funds pay for playground equipment?", desc: "A school or district must determine whether a proposed cost is allowable, necessary, reasonable and connected to its approved Title I plan. Equipment is not automatically eligible simply because a school receives Title I funds; obtain written local approval before purchase." },
      { title: "What should a playground grant application include?", desc: "Include the student need, beneficiaries, intended use, floor plan, phased scope, safety and access basis, supplier quote, implementation schedule, maintenance owner and a plan for any funding gap." },
      { title: "Should a school fund the project in phases?", desc: "Yes, if every phase can open safely and independently. Complete surfacing, access, circulation and the core structure first, then add pre-engineered modules without moving exits or creating new fall zones." },
      { title: "How do we prevent fundraising from missing hidden costs?", desc: "Request a scope that separates equipment, surfacing, freight, site preparation, installation, inspection, spare parts and taxes. A fundraising target based only on equipment price is usually incomplete." },
      { title: "What can a manufacturer provide for approval?", desc: "We can provide a 3D perspective, layout, phased equipment schedule, itemized quote, applicable test-document list, lead-time plan and installation boundary for your internal review." },
    ],
  },

  specialEducation: {
    slug: "inclusive-indoor-play-equipment-special-education",
    title: "Inclusive Indoor Play Equipment for Special Education",
    metaTitle: "Indoor Play Equipment for Special Education",
    metaDescription: "Specify special education indoor play equipment using student profiles, regulation zones, accessible routes, staff sightlines and documented goals.",
    keywords: ["inclusive indoor play equipment for special education", "special education play equipment", "adaptive indoor playground equipment", "sensory play equipment for schools"],
    kicker: "Special Education · IEP Support · Staff-Led Sessions",
    description: "A procurement framework for special-education teams selecting indoor play equipment around student profiles, regulation needs, transfer routes, communication goals and staff supervision—not around a generic sensory-room checklist.",
    primaryCta: "Plan a Special Education Zone",
    secondaryCta: "Review the Selection Framework",
    heroImage: productImages.softPlay,
    heroImageAlt: "3D perspective of inclusive soft play equipment for a special education setting",
    metrics: [
      { value: "3 states", label: "Alert, engage and regulate" },
      { value: "2 routes", label: "Alternative access to shared activities" },
      { value: "Clear view", label: "Staff sightline across every zone" },
      { value: "1 plan", label: "Equipment mapped to student goals" },
    ],
    frameworkTitle: "Select Equipment From Student Needs, Not Diagnoses",
    frameworkIntro: "Two students with the same diagnosis may need opposite sensory input. Build the brief from observable needs, support level, communication style and session goals, then test each equipment choice against staffing and transitions.",
    framework: [
      { title: "1. Profile participation needs", desc: "Record mobility, transfer support, sensory seeking or avoidance, communication method, elopement risk and whether one-to-one assistance is required. Use de-identified group profiles rather than medical labels in supplier documents." },
      { title: "2. Match input to a goal", desc: "Connect movement, deep pressure, tactile play or quiet retreat to a defined session goal such as readiness, motor planning, turn-taking or transition—not to an unsupported therapeutic promise." },
      { title: "3. Design staff positions", desc: "Mark where adults stand, assist transfers and intercept exits. Open frames, low dividers and two-way circulation help staff support a group without turning every activity into one-to-one supervision." },
      { title: "4. Trial the transition", desc: "Review arrival, shoes and belongings, movement between high- and low-input zones, and exit to class. A good activity can fail if the transition path is noisy, narrow or visually confusing." },
    ],
    equipmentTitle: "Equipment Roles in a Staff-Led Special Education Session",
    equipmentIntro: "These are functional roles, not a universal prescription. The education and therapy team should approve the final mix for its students.",
    equipment: [
      { title: "Ground-level cooperative play", desc: "Cause-and-effect panels, ball activities and role-play surfaces that allow seated and standing students to participate together." },
      { title: "Low-height motor planning", desc: "Wide steps, crawl tunnels, ramps and supported balance routes with an obvious entry, exit and bypass." },
      { title: "Proprioceptive work", desc: "Resistance tunnels, soft push blocks and crash-pad activities that can be used under staff direction." },
      { title: "Controlled movement input", desc: "Low swing, rocker or mini-trampoline stations positioned away from quiet areas and operated under the school's supervision plan." },
      { title: "Calm retreat", desc: "An acoustically softened, low-glare space with a visible opening so a student can regulate without becoming isolated from staff." },
      { title: "Visual sequence supports", desc: "Colour-coded entries, first/then boards and picture-based station markers that make the route predictable for non-readers." },
    ],
    audienceTitle: "Who Should Approve the Equipment Brief",
    audienceIntro: "The safest specification combines the people who understand students, daily operation, facilities and compliance.",
    audience: [
      { title: "Special education teachers", desc: "Define group routines, communication supports, transition risks and activities that can be repeated during instruction." },
      { title: "Occupational and physical therapy teams", desc: "Review movement demands, transfer points and any student-specific use restrictions within their professional scope." },
      { title: "District facilities and safety teams", desc: "Confirm circulation, egress, surfacing, anchoring, cleaning and inspection responsibilities." },
      { title: "Administrators and procurement", desc: "Require a clear specification, test-document list, warranty boundaries and replacement-parts plan before award." },
    ],
    gallery: [
      { src: productImages.softPlay, alt: "3D perspective of a low-height inclusive soft play zone", caption: "Low-height routes can offer steps, ramps and bypasses within the same activity." },
      { src: projectImages.softPlayProject, alt: "Soft play equipment with tactile and ground-level activities", caption: "Ground-level play keeps more students participating in the same group session." },
      { src: projectImages.indoorProject, alt: "Indoor play structure with open staff sightlines", caption: "Open visibility and simple circulation reduce hidden areas during staff-led use." },
    ],
    specTable: {
      heading: "Match Equipment Roles to Observable Needs",
      caption: "Special education play equipment selection matrix",
      columns: ["Observed need", "Equipment role", "Layout requirement", "Staff review"],
      rows: [
        ["Needs predictable sequence", "Visual station route", "One-way flow with bypass", "Communication support"],
        ["Seeks heavy work", "Resistance and push activity", "Clear landing space", "Use duration"],
        ["Avoids noise or glare", "Calm retreat", "Separated from active zone", "Re-entry routine"],
        ["Uses mobility support", "Ground-level shared play", "Accessible route and turn space", "Transfer method"],
        ["Elopement risk", "Contained activity loop", "Controlled entry and clear view", "Staff position"],
      ],
      footnote: "Equipment supports an education plan but does not diagnose, treat or replace professional therapy.",
    },
    sources: [sources.idea, sources.ada, sources.cpsc, sources.astmF1487],
    related: [
      { label: "Inclusive play center design", href: "/inclusive-play-center-design-for-children" },
      { label: "Accessible playground design", href: "/accessible-indoor-playground-design-for-disabilities" },
      { label: "Sensory play area design", href: "/designing-sensory-play-areas-for-education" },
      { label: "Durable soft play for Title I schools", href: "/durable-soft-play-equipment-title-1-schools" },
      { label: "School playground funding guide", href: "/how-to-fund-school-playground-equipment" },
    ],
    faq: [
      { title: "What makes indoor play equipment suitable for special education?", desc: "It offers more than one way to participate, supports predictable transitions, preserves staff sightlines, provides an exit or bypass, and maps each activity to a documented educational or participation goal." },
      { title: "Is sensory equipment the same as inclusive equipment?", desc: "No. Sensory equipment provides specific kinds of input. Inclusive equipment also addresses access, communication, shared participation, difficulty choice and the ability to leave an activity without disrupting the group." },
      { title: "Can equipment be specified from a diagnosis list?", desc: "A diagnosis alone is not enough. Use observable needs and the school's professional guidance because students with the same diagnosis can respond differently to sound, movement, touch and enclosure." },
      { title: "Which documents should a school request?", desc: "Request layout and sightline drawings, intended-age information, applicable test reports, surfacing requirements, installation instructions, cleaning guidance, inspection schedules and replacement-part information." },
      { title: "Can NinescapeLand work with a school's therapy team?", desc: "Yes. We can convert the team's functional requirements into equipment zones and a 3D perspective for review, while the school's qualified professionals retain authority over student-specific use." },
    ],
  },

  free3d: {
    slug: "free-3d-design-for-indoor-play-center",
    title: "Free 3D Design for an Indoor Play Center",
    metaTitle: "Free 3D Design for Indoor Play Centers",
    metaDescription: "See what an indoor play center 3D design should include: site inputs, perspective renders, equipment schedule, safety review, revisions and build handoff.",
    keywords: ["free 3d design for indoor play center", "indoor playground 3d design", "indoor play center layout design", "playground concept rendering"],
    kicker: "Design Brief · 3D Perspectives · Build Handoff",
    description: "A clear guide to the free 3D concept stage: what to send, what a useful design package should show, which decisions belong before the render and how the approved concept becomes a manufacturable equipment schedule.",
    primaryCta: "Start My 3D Concept",
    secondaryCta: "See Required Inputs",
    heroImage: heroImages.process,
    heroImageAlt: "3D perspective rendering of a custom indoor play center",
    metrics: [
      { value: "6 inputs", label: "Site facts needed before design" },
      { value: "2 views", label: "Perspective angles for review" },
      { value: "1 schedule", label: "Equipment list tied to the concept" },
      { value: "3 gates", label: "Concept, safety and production approval" },
    ],
    frameworkTitle: "Make the 3D Render a Decision Tool, Not Decoration",
    frameworkIntro: "A convincing image is only useful when it reflects the real column grid, ceiling, entrances, exits, target ages and operating model. The design process should resolve constraints before adding visual detail.",
    framework: [
      { title: "1. Submit a buildable brief", desc: "Provide a dimensioned plan, clear ceiling heights, columns, doors, stairs, service rooms, target age bands and attraction priorities. Photographs help explain obstructions that a simple plan may miss." },
      { title: "2. Lock circulation and zones", desc: "Agree entry control, parent seating, toddler separation, staff views and emergency routes in a blocking layout before detailed theming. This prevents attractive renders that cannot be operated." },
      { title: "3. Review safety assumptions", desc: "Check intended ages, fall zones, transfer routes, access, capacity and the standard used for the destination market. Record open issues directly on the drawing." },
      { title: "4. Convert concept to production", desc: "After concept approval, freeze dimensions and issue the equipment schedule, structural details, colour references, interfaces and revision record needed by manufacturing and the site team." },
    ],
    equipmentTitle: "What a Useful 3D Design Package Contains",
    equipmentIntro: "The deliverables below help owners, architects, contractors and operators review the same proposal before any equipment is manufactured.",
    equipment: [
      { title: "Dimensioned zoning layout", desc: "Equipment footprint, circulation, entrances, exits, columns, seating and service boundaries on the supplied building plan." },
      { title: "Entry perspective", desc: "The guest view from reception showing visibility, visual hierarchy and the relationship between play, seating and control points." },
      { title: "Operational perspective", desc: "A second view from the parent or staff position to expose blind spots, queues and overlapping age zones." },
      { title: "Equipment schedule", desc: "Named modules and quantities tied to the design so the quote and the image describe the same scope." },
      { title: "Materials and colour board", desc: "Steel coating, foam, vinyl, nets, graphics and key colour references suitable for brand and maintenance review." },
      { title: "Open-issue register", desc: "Items still awaiting landlord, engineer, inspector or client confirmation before the design can be released for manufacture." },
    ],
    audienceTitle: "Who Uses the 3D Concept Before Ordering",
    audienceIntro: "A shared visual package reduces rework because every decision-maker can review the same layout from their own perspective.",
    audience: [
      { title: "Owners and investors", desc: "Confirm the attraction mix, customer journey and visible value before committing capital." },
      { title: "Architects and contractors", desc: "Coordinate columns, ceiling services, power, fire systems, floor build-up and installation access." },
      { title: "Operators", desc: "Test reception control, staff views, queues, party movement, cleaning access and opening capacity." },
      { title: "Landlords and reviewers", desc: "Understand the intended fit-out, appearance and interfaces without reading a product catalogue." },
    ],
    gallery: [
      { src: heroImages.process, alt: "3D perspective showing an indoor play center concept", caption: "A perspective should reflect the actual building constraints and attraction mix." },
      { src: productImages.indoorPlayground, alt: "3D rendered indoor playground with multi-level play zones", caption: "The equipment schedule must match every major element visible in the approved concept." },
      { src: productImages.trampolinePark, alt: "3D perspective of a trampoline park equipment layout", caption: "Separate review views help expose circulation, supervision and queue conflicts." },
    ],
    specTable: {
      heading: "Concept Render vs Production Design",
      intro: "Both are valuable, but they answer different questions and should not be confused.",
      caption: "Indoor play center design stage comparison",
      columns: ["Deliverable", "Concept stage", "Production stage", "Primary reviewer"],
      rows: [
        ["Purpose", "Choose layout and experience", "Define what will be built", "Owner / manufacturer"],
        ["Geometry", "Accurate overall envelope", "Component and connection detail", "Architect / engineer"],
        ["Visuals", "Perspective and colour intent", "Final materials and references", "Brand / production"],
        ["Safety", "Risks and required clearances", "Recorded calculations and documents", "Safety reviewer"],
        ["Changes", "Fast option comparison", "Controlled revision process", "Project manager"],
      ],
      footnote: "A free concept does not replace project-specific engineering, local authority review or final production drawings.",
    },
    sources: [sources.cpsc, sources.astmF1918, sources.astmF2970, sources.ada],
    related: [
      { label: "Custom playground cost guide", href: "/custom-indoor-playground-cost-free-3d-design" },
      { label: "Complete play center solutions", href: "/complete-indoor-play-center-solutions" },
      { label: "Themed indoor playground design", href: "/themed-indoor-playground-design" },
      { label: "Indoor playground business plan", href: "/indoor-playground-business-plan" },
      { label: "School playground funding guide", href: "/how-to-fund-school-playground-equipment" },
    ],
    faq: [
      { title: "What information is needed for a free 3D design?", desc: "Send a dimensioned floor plan, clear ceiling heights, columns and obstructions, door and stair positions, target ages, attraction priorities and your brand or theme direction. Photos and a short operating brief improve accuracy." },
      { title: "What should the 3D design include?", desc: "It should include a dimensioned zoning layout, at least two useful perspectives, an equipment schedule, key material and colour references, and a list of assumptions or issues that still require approval." },
      { title: "Is a 3D render ready for construction?", desc: "No. It is a concept decision tool. Manufacturing requires final dimensions, structural details, connection points, material specifications, interfaces and a controlled approval record." },
      { title: "How do we compare two design options?", desc: "Use the same criteria for both: capacity, age separation, circulation, staff sightlines, accessible participation, attraction mix, operational complexity and the scope included in the quote." },
      { title: "Does NinescapeLand charge for the first concept?", desc: "NinescapeLand offers an initial 3D concept for qualified commercial projects after receiving the site information and project brief. Confirm the included views, revisions and next-stage deliverables with the project team." },
    ],
  },

  titleI: {
    slug: "durable-soft-play-equipment-title-1-schools",
    title: "Durable Soft Play Equipment for Title I Schools",
    metaTitle: "Durable Soft Play Equipment for Title I Schools",
    metaDescription: "Choose durable soft play for Title I schools using repairable covers, replaceable modules, cleaning access and lifecycle documentation.",
    keywords: ["durable soft play equipment for title 1 schools", "school soft play equipment", "low maintenance soft play", "commercial soft play for schools"],
    kicker: "High Use · Repairable Parts · Budget-Aware Procurement",
    description: "A durability-first specification for schools serving high daily use: repairable wear surfaces, replaceable modules, accessible cleaning points and lifecycle documentation that protect limited budgets after installation.",
    primaryCta: "Request a Durable Soft Play Spec",
    secondaryCta: "Review Durability Priorities",
    heroImage: productImages.softPlay,
    heroImageAlt: "3D perspective of durable modular soft play equipment for a school",
    metrics: [
      { value: "6 checks", label: "Durability points before award" },
      { value: "Modular", label: "Replace damaged parts without a rebuild" },
      { value: "Daily", label: "Cleanable high-touch surfaces" },
      { value: "Logged", label: "Inspection and repair history" },
    ],
    frameworkTitle: "Buy for the Fifth Year, Not Only Opening Day",
    frameworkIntro: "Durability is not a vague promise. It is the ability to inspect, clean, repair and replace the parts that wear fastest without closing the entire area or buying a new structure.",
    framework: [
      { title: "1. Identify the wear path", desc: "Mark entries, slide exits, crawl points, step edges and staff access. These surfaces receive repeated contact and should use replaceable skins, edge protection and accessible fasteners." },
      { title: "2. Specify replaceable modules", desc: "Require part references for foam forms, vinyl covers, nets, mats and connectors. A damaged component should be removable without dismantling the full structure." },
      { title: "3. Design for cleaning access", desc: "Avoid sealed corners that trap debris. Provide liftable mats where appropriate, reachable undersides, drain-safe cleaning guidance and material compatibility information." },
      { title: "4. Price the support package", desc: "Compare the included spare-parts kit, warranty exclusions, response process and expected replacement items alongside the purchase price." },
    ],
    equipmentTitle: "Durability Features Worth Naming in the RFP",
    equipmentIntro: "Use measurable construction and service requirements instead of asking only for 'commercial grade'.",
    equipment: [
      { title: "Replaceable vinyl sleeves", desc: "High-contact padded posts and rails use removable covers so a torn surface can be changed without replacing the foam core." },
      { title: "Modular foam forms", desc: "Steps, wedges, tunnels and balance pieces carry individual part references for targeted replacement or rotation." },
      { title: "Protected high-wear edges", desc: "Entry lips, slide run-outs and crawl openings receive reinforced seams and sacrificial wear layers." },
      { title: "Accessible net connections", desc: "Net panels and cable ties can be inspected and replaced from a service position without entering closed cavities." },
      { title: "Cleanable floor build-up", desc: "Mats are sealed or removable according to the cleaning plan, with no exposed absorbent core in normal use." },
      { title: "Starter spare-parts kit", desc: "Matching cover material, ties, fasteners and named high-wear parts are supplied for controlled minor repairs." },
    ],
    audienceTitle: "School Buyers Balancing Use and Limited Budgets",
    audienceIntro: "The same durability brief supports schools regardless of funding source; Title I status does not determine product eligibility or replace local purchasing approval.",
    audience: [
      { title: "Title I school leaders", desc: "Build a durable, documented scope that can be reviewed against the schoolwide plan and local allowable-use rules." },
      { title: "District purchasing teams", desc: "Compare construction, parts support and lifecycle cost across bids rather than accepting a generic warranty statement." },
      { title: "Facilities and custodial teams", desc: "Review cleaning access, inspection points and repair methods before the equipment arrives." },
      { title: "Education foundations and PTAs", desc: "Fund complete, serviceable modules whose future upkeep is understood by the school." },
    ],
    gallery: [
      { src: productImages.softPlay, alt: "3D perspective of modular soft play equipment built for school use", caption: "Modular construction allows high-wear pieces to be replaced independently." },
      { src: projectImages.softPlayProject, alt: "Close view of soft play covers and padded edges", caption: "Reinforced, accessible wear surfaces simplify inspection and repair." },
      { src: projectImages.indoorProject, alt: "School indoor play area with clear cleaning access", caption: "Open service access matters throughout the equipment lifecycle." },
    ],
    specTable: {
      heading: "Evaluate Durability Beyond the Warranty",
      caption: "Durable school soft play procurement comparison",
      columns: ["RFP question", "Weak response", "Stronger evidence", "Why it matters"],
      rows: [
        ["Can covers be replaced?", "Whole unit replacement", "Named removable cover parts", "Reduces closure scope"],
        ["How is wear inspected?", "Visual check only", "Marked inspection points and schedule", "Finds damage earlier"],
        ["What spares are supplied?", "Available on request", "Itemized starter kit and lead times", "Speeds minor repairs"],
        ["How is cleaning performed?", "Use normal cleaner", "Material-specific written method", "Protects surfaces"],
        ["What does warranty exclude?", "General statement", "Component-level terms", "Supports fair bid comparison"],
      ],
      footnote: "Title I and other education funds are governed by program and local rules. Confirm allowable use before procurement.",
    },
    sources: [sources.titleI, sources.cpsc, sources.astmF1918, sources.astmF1487],
    related: [
      { label: "School playground funding guide", href: "/how-to-fund-school-playground-equipment" },
      { label: "Custom soft play manufacturer for schools", href: "/custom-soft-play-equipment-manufacturer-for-schools" },
      { label: "Indoor playground total cost of ownership", href: "/indoor-playground-total-cost-of-ownership" },
      { label: "Special education play equipment", href: "/inclusive-indoor-play-equipment-special-education" },
      { label: "Maintenance and warranty", href: "/maintenance-warranty" },
    ],
    faq: [
      { title: "What makes soft play equipment durable for school use?", desc: "Look for replaceable covers and modules, reinforced high-wear edges, accessible inspection points, documented cleaning compatibility, available spare parts and a component-level warranty." },
      { title: "Can a Title I school use Title I funds for soft play?", desc: "The school or district must decide whether the expense is allowable and aligned with its approved plan. Title I status alone does not make equipment eligible; secure written program and procurement approval first." },
      { title: "What should be included in a school RFP?", desc: "State user ages, expected schedule, site dimensions, applicable standard, cleaning method, replaceable-parts requirement, spare-parts list, warranty terms, installation scope and required handover documents." },
      { title: "How can schools reduce long-term repair cost?", desc: "Choose modular parts with identifiers, protect predictable wear points, keep a starter spares kit, follow a recorded inspection schedule and require replacement lead times in the bid." },
      { title: "Can existing soft play be upgraded for durability?", desc: "Often yes. Covers, floor mats, nets and some foam modules can be replaced independently after a site and compatibility review. Structural damage requires a separate engineering assessment." },
    ],
  },

  trampolineSupplier: {
    slug: "astm-certified-commercial-trampoline-park-supplier",
    title: "ASTM Commercial Trampoline Park Supplier Checklist",
    metaTitle: "ASTM Trampoline Park Supplier Checklist",
    metaDescription: "Prequalify a commercial trampoline park supplier using ASTM F2970 scope, test evidence, drawing control, batch traceability and handover documentation.",
    keywords: ["commercial indoor trampoline park supplier astm certified", "ASTM trampoline park supplier", "commercial trampoline park equipment", "trampoline supplier checklist"],
    kicker: "Supplier Prequalification · ASTM F2970 · Handover Evidence",
    description: "A buyer-side checklist for comparing commercial trampoline park suppliers: verify the applicable ASTM scope, trace reports to the quoted configuration, control drawing revisions and make compliance evidence a contractual deliverable.",
    primaryCta: "Request Our ASTM Document Pack",
    secondaryCta: "Use the Supplier Checklist",
    heroImage: productImages.trampolinePark,
    heroImageAlt: "3D perspective of a commercial indoor trampoline park equipment package",
    metrics: [
      { value: "5 gates", label: "Supplier qualification checkpoints" },
      { value: "F2970", label: "Core trampoline-court reference" },
      { value: "Per order", label: "Drawing and document traceability" },
      { value: "Before pay", label: "Handover evidence as a milestone" },
    ],
    frameworkTitle: "Qualify the Supplier Before Comparing the Price",
    frameworkIntro: "A standards logo on a brochure does not prove that the quoted layout, materials or delivered batch match tested equipment. Prequalification should connect every claim to a document, drawing and responsible party.",
    framework: [
      { title: "1. Define the applicable scope", desc: "Confirm the destination, attraction mix and local reviewer. ASTM F2970 addresses commercial trampoline courts, while climbing, soft play, surfacing and building work may require separate standards and approvals." },
      { title: "2. Trace evidence to the quote", desc: "Match report numbers, product descriptions, material grades and tested configurations to the proposed equipment. Ask the supplier to identify any project-specific deviations." },
      { title: "3. Control the approved drawing", desc: "Use a revision register for bed layout, platform heights, padding, enclosure, exits and interfaces. Production must reference the final signed version, not an earlier sales render." },
      { title: "4. Audit production and handover", desc: "Agree inspection hold points, batch records, packing identification, installation responsibilities and the final document index before paying the last milestone." },
    ],
    equipmentTitle: "Evidence to Request by Trampoline Attraction",
    equipmentIntro: "Different attractions create different risks, so one generic certificate should never be accepted as the complete project file.",
    equipment: [
      { title: "Main court", desc: "Bed, spring, frame and padding specifications tied to the approved bay layout and intended user rules." },
      { title: "Dodgeball court", desc: "Court separation, wall padding, enclosure and operating-capacity assumptions recorded on the drawing." },
      { title: "Basketball lanes", desc: "Backboard and hoop padding, landing area, adjacent-user separation and equipment anchoring details." },
      { title: "Airbag or landing system", desc: "Manufacturer instructions, operating pressure where applicable, anchoring, inspection and shutdown procedure." },
      { title: "Ninja and climbing add-ons", desc: "Separate fall-zone, anchor and component evidence matched to each non-trampoline activity." },
      { title: "Access and control system", desc: "Entry points, rules signs, staff positions, emergency routes and capacity assumptions included in the operating handoff." },
    ],
    audienceTitle: "Buyers Who Need a Defensible Supplier File",
    audienceIntro: "The checklist supports procurement decisions; the final approval remains with the project's qualified local reviewers and authorities.",
    audience: [
      { title: "Independent park owners", desc: "Compare suppliers on documented scope and handover quality before committing a deposit." },
      { title: "FEC chains and franchise teams", desc: "Standardize drawing approval, component evidence and replacement-parts data across locations." },
      { title: "Architects and project managers", desc: "Coordinate equipment, building, fire, electrical and installation interfaces from one controlled drawing set." },
      { title: "Inspectors and insurers", desc: "Receive an indexed file that identifies the delivered configuration and the operator's ongoing responsibilities." },
    ],
    gallery: [
      { src: productImages.trampolinePark, alt: "3D perspective of an ASTM-planned commercial trampoline park", caption: "The approved layout should identify each court, access point and adjacent attraction." },
      { src: projectImages.trampolineProject, alt: "Commercial trampoline park rendering showing padded courts", caption: "Padding, enclosure and interfaces must remain controlled through drawing revisions." },
      { src: projectImages.bouncePark, alt: "Trampoline basketball zone with separated landing area", caption: "Add-on attractions require their own layout and evidence review." },
    ],
    specTable: {
      heading: "Commercial Trampoline Supplier Prequalification",
      caption: "ASTM trampoline park supplier evidence checklist",
      columns: ["Checkpoint", "Document to request", "What to verify", "Contract milestone"],
      rows: [
        ["Standard scope", "Applicable-standard matrix", "Every attraction is covered", "Before quotation approval"],
        ["Test evidence", "Reports and certificate references", "Matches material and configuration", "Before deposit"],
        ["Design control", "Signed revision register", "Production uses final drawing", "Before manufacture"],
        ["Production quality", "Inspection and batch records", "Components are traceable", "Before shipment"],
        ["Handover", "Indexed as-built file", "Install, inspect and maintain", "Before final payment"],
      ],
      footnote: "Certification requirements vary by jurisdiction. Confirm the final standard set with local authorities, inspectors and insurers.",
    },
    sources: [sources.astmF2970, sources.cpsc, sources.astmF1487],
    related: [
      { label: "Trampoline park safety standards", href: "/safety-standards-for-trampoline-park-equipment" },
      { label: "TUV supplier verification", href: "/tuv-certified-playground-equipment-supplier" },
      { label: "Commercial trampoline park equipment", href: "/products/trampoline-park" },
      { label: "Complete play center solutions", href: "/complete-indoor-play-center-solutions" },
      { label: "Maintenance and warranty", href: "/maintenance-warranty" },
    ],
    faq: [
      { title: "What should an ASTM trampoline park supplier provide?", desc: "Request an applicable-standard matrix, referenced test reports, approved project drawings, material and batch records, installation instructions, inspection schedules, as-built documents and replacement-parts information." },
      { title: "Does ASTM F2970 cover every attraction in a trampoline park?", desc: "No. It addresses commercial trampoline courts. Climbing, ninja, soft play, surfacing, electrical systems and the building itself may require other standards and local approvals." },
      { title: "How can a buyer verify that a report applies to the quoted park?", desc: "Match the report's product description, material grades and tested configuration to the quote and drawing. Ask the supplier to list every deviation and the evidence used for that change." },
      { title: "When should compliance documents be delivered?", desc: "Agree the index before contract, review core evidence before deposit, approve drawings before production and make the complete as-built handover file a condition of final payment." },
      { title: "Is a supplier certificate enough for local approval?", desc: "Usually not by itself. Local authorities, inspectors and insurers may require project-specific drawings, installation records, operating procedures and additional standards. Confirm their requirements early." },
    ],
  },

  ninjaEducation: {
    slug: "ninja-course-equipment-indoor-education-centers",
    title: "Ninja Course Equipment for Education Centers",
    metaTitle: "Ninja Course Equipment for Education Centers",
    metaDescription: "Plan ninja course equipment for education centers with skill progressions, class rotations, open sightlines, reset rules and measurable movement outcomes.",
    keywords: ["ninja course equipment for indoor education centers", "ninja course equipment", "school ninja obstacle course", "educational ninja course"],
    kicker: "Skill Progressions · Class Rotation · Teacher Visibility",
    description: "A curriculum-led approach to indoor ninja equipment: turn obstacles into repeatable skill stations with beginner-to-advanced progressions, class-sized rotations, clear staff positions and simple achievement records.",
    primaryCta: "Design an Education Ninja Course",
    secondaryCta: "See the Curriculum Framework",
    heroImage: productImages.ninjaCourse,
    heroImageAlt: "3D perspective of ninja course equipment arranged for an education center",
    metrics: [
      { value: "3 levels", label: "Progression at every core skill" },
      { value: "4–6", label: "Students active per station loop" },
      { value: "Visible", label: "Start, finish and staff position" },
      { value: "Recorded", label: "Completion and technique progress" },
    ],
    frameworkTitle: "Build a Course That Can Be Taught",
    frameworkIntro: "Education centers need more than a dramatic obstacle. Each station should teach a named movement skill, offer a clear progression and fit a repeatable lesson structure.",
    framework: [
      { title: "1. Define the skill map", desc: "Group obstacles under grip, hang, traverse, balance, jump, crawl and landing. Avoid several attractions testing the same skill while leaving another skill absent." },
      { title: "2. Create three progressions", desc: "Give each core skill an entry task, a developing task and a challenge task. Students can train together while working at an appropriate level." },
      { title: "3. Engineer the class rotation", desc: "Set station capacity, attempt time, bypass route and waiting position so a class rotates without long queues or students crossing active landing zones." },
      { title: "4. Record repeatable outcomes", desc: "Track controlled completion, technique or consistency rather than only fastest time. This gives educators evidence of progress without turning every session into a race." },
    ],
    equipmentTitle: "Six Skill Stations for an Education Ninja Loop",
    equipmentIntro: "The mix balances upper-body, lower-body and planning tasks while keeping transitions visible and teachable.",
    equipment: [
      { title: "Grip and hang station", desc: "Low rings, bars or holds with adjustable reach distances and a clearly marked controlled dismount." },
      { title: "Traverse station", desc: "Horizontal movement across nets, holds or suspended steps with three route choices and a bypass." },
      { title: "Balance station", desc: "Ground-level beam, wobble element and separated stepping route progressing from stable to dynamic." },
      { title: "Jump and landing station", desc: "Marked take-off and landing targets that prioritize controlled landing before distance or speed." },
      { title: "Crawl and spatial station", desc: "Tunnels and low obstacles that develop body awareness without hidden supervision areas." },
      { title: "Timed application lane", desc: "A short final sequence combining learned skills; time is optional and never replaces technique criteria." },
    ],
    audienceTitle: "Education Programs That Need Progression, Not Spectacle",
    audienceIntro: "This format suits providers that teach recurring groups and need visible development across a term.",
    audience: [
      { title: "Indoor education centers", desc: "Add a structured movement course that can be scheduled alongside tutoring or enrichment programs." },
      { title: "School PE departments", desc: "Use skill stations for class rotation, assessment and mixed-ability participation." },
      { title: "After-school programs", desc: "Run repeatable achievement levels that give returning students a clear next challenge." },
      { title: "Gymnastics and youth fitness clubs", desc: "Extend grip, balance and movement-planning programs with a modular obstacle lane." },
    ],
    gallery: [
      { src: productImages.ninjaCourse, alt: "3D perspective of an educational ninja obstacle course", caption: "A clear loop keeps starts, finishes and waiting positions visible." },
      { src: projectImages.ninjaProject, alt: "Ninja course obstacle details with graded challenge options", caption: "Three progressions let a mixed-ability group train the same skill together." },
      { src: projectImages.indoorProject, alt: "Indoor education center play zone with open supervision", caption: "Open frames and separated landings support teacher-led station rotation." },
    ],
    specTable: {
      heading: "Turn Obstacles Into a Skill Progression",
      caption: "Education ninja course skill matrix",
      columns: ["Skill", "Entry task", "Developing task", "Challenge task"],
      rows: [
        ["Grip", "Supported bar hold", "Ring transfer", "Variable hold traverse"],
        ["Balance", "Wide ground beam", "Wobble beam", "Separated moving steps"],
        ["Traverse", "Low net route", "Angled holds", "Suspended route"],
        ["Jump / land", "Two-foot target", "Direction change", "Linked targets"],
        ["Planning", "Single sequence", "Choice of two routes", "Timed mixed sequence"],
      ],
      footnote: "Final obstacle dimensions, fall protection and supervision rules must match user age, ability and the applicable local standard.",
    },
    sources: [sources.shape, sources.cpsc, sources.astmF1487],
    related: [
      { label: "Ninja course equipment", href: "/products/ninja-course" },
      { label: "Indoor PE equipment for schools", href: "/indoor-pe-equipment-for-schools" },
      { label: "After-school program equipment", href: "/after-school-program-indoor-play-equipment" },
      { label: "Interactive learning play equipment", href: "/interactive-play-equipment-for-learning-centers" },
      { label: "Special education play equipment", href: "/inclusive-indoor-play-equipment-special-education" },
    ],
    faq: [
      { title: "How is an education ninja course different from a commercial attraction?", desc: "It is organized around named skills, graded progressions, class rotation and observable outcomes. Spectacle and speed are secondary to repeatable teaching and controlled participation." },
      { title: "Which skills can ninja equipment support?", desc: "A balanced course can support grip, hanging, traversing, balance, jumping, controlled landing, crawling, bilateral coordination and movement planning." },
      { title: "How do mixed-ability students use one course?", desc: "Place entry, developing and challenge versions of the same skill side by side, provide a bypass, and assess control or consistency rather than requiring every student to complete the hardest route." },
      { title: "How should a class rotate through the course?", desc: "Define each station's active capacity, attempt time, waiting point and next movement. Separate waiting students from landings and avoid routes that cross each other." },
      { title: "Can the course fit an existing education center?", desc: "Yes. Send the floor plan, ceiling heights, columns, user ages, class size and lesson length. We can prepare a 3D concept with station capacity, circulation and progressions marked for review." },
    ],
  },

  completeSolution: {
    slug: "complete-indoor-play-center-solutions",
    title: "Complete Indoor Play Center Solutions",
    metaTitle: "Complete Indoor Play Center Solutions",
    metaDescription: "Plan a complete indoor play center from brief and 3D design through equipment, logistics, installation, handover and opening support with clear ownership.",
    keywords: ["complete play center solutions since 2008", "complete indoor play center solution", "turnkey indoor playground supplier", "indoor play center project delivery"],
    kicker: "Brief to Opening · One Scope · Controlled Handover",
    description: "A project-delivery framework for owners who need design, equipment, documentation, logistics, installation coordination and opening handover managed as one connected scope—with responsibilities visible before contract.",
    primaryCta: "Plan a Complete Play Center",
    secondaryCta: "Review the Delivery Framework",
    heroImage: heroImages.home,
    heroImageAlt: "3D perspective of a complete multi-zone indoor play center solution",
    metrics: [
      { value: "6 stages", label: "Brief through opening handover" },
      { value: "1 register", label: "Scope, decisions and responsibilities" },
      { value: "3 reviews", label: "Concept, production and site readiness" },
      { value: "Indexed", label: "Final as-built document package" },
    ],
    frameworkTitle: "Define the Complete Scope Before Splitting Responsibilities",
    frameworkIntro: "Turnkey should not mean vague. A complete solution names every deliverable, interface, approval and exclusion from the first brief to the final inspection file.",
    framework: [
      { title: "1. Feasibility and brief", desc: "Confirm site envelope, market, target ages, capacity, attraction mix, operating model, budget boundary and local review path before concept work begins." },
      { title: "2. Design and coordinated approval", desc: "Develop zoning, perspectives and equipment schedules while tracking interfaces with the architect, landlord, structure, fire systems, electrical work and flooring." },
      { title: "3. Manufacture and logistics", desc: "Freeze revisions, inspect production, identify packed components, plan containers and define customs and delivery responsibilities under the agreed trade terms." },
      { title: "4. Installation and handover", desc: "Verify site readiness, sequence assembly, record changes, complete inspection actions, train the operator and hand over indexed as-built and maintenance documents." },
    ],
    equipmentTitle: "Six Connected Workstreams in a Complete Solution",
    equipmentIntro: "The value comes from coordinating interfaces—not simply selling more equipment categories.",
    equipment: [
      { title: "Play strategy and zoning", desc: "Age mix, capacity, dwell time, supervision and revenue-supporting adjacencies translated into one operational layout." },
      { title: "3D concept and specification", desc: "Perspective views, equipment schedule, materials, applicable standards and an open-issue register for coordinated approval." },
      { title: "Multi-category equipment", desc: "Indoor playground, soft play, trampoline, ninja and interactive zones designed to share circulation and operating rules." },
      { title: "Production quality control", desc: "Approved drawings, material references, inspections, component identification and packing records connected to the order." },
      { title: "Logistics and site interfaces", desc: "Container plan, delivery sequence, unloading needs, installation access and clear division between equipment and local building work." },
      { title: "Opening handover", desc: "As-built drawings, manuals, inspection points, spare-parts list, training topics and unresolved actions collected in one index." },
    ],
    audienceTitle: "Projects That Benefit From One Coordinated Scope",
    audienceIntro: "Complete delivery is most useful when several stakeholders and attraction types must reach opening day together.",
    audience: [
      { title: "First-time play center owners", desc: "Use one responsibility matrix to understand which decisions belong to the supplier, local team and authorities." },
      { title: "Family entertainment centers", desc: "Coordinate multiple attractions, party flow, seating and support spaces around one operating plan." },
      { title: "Mall, hotel and resort developers", desc: "Integrate equipment with landlord, architecture, fire, structure and opening-program requirements." },
      { title: "Multi-site operators", desc: "Standardize approvals and handover while allowing site-specific dimensions, themes and local compliance." },
    ],
    gallery: [
      { src: heroImages.home, alt: "3D perspective of a complete indoor play center with multiple activity zones", caption: "A complete concept coordinates attractions, circulation, seating and supervision." },
      { src: productImages.trampolinePark, alt: "3D perspective of a trampoline zone within a complete play center", caption: "Multi-category equipment must share clear boundaries and operating rules." },
      { src: projectImages.fecCenter, alt: "Indoor family entertainment center project detail", caption: "The handover package connects the approved design to the installed result." },
    ],
    specTable: {
      heading: "Responsibility Matrix for Complete Delivery",
      caption: "Indoor play center project responsibility comparison",
      columns: ["Workstream", "Equipment partner", "Local project team", "Joint approval"],
      rows: [
        ["Concept and equipment layout", "Lead", "Site inputs", "Owner sign-off"],
        ["Building and fire design", "Provide interfaces", "Lead", "Authority review"],
        ["Manufacture and packing", "Lead", "Witness if agreed", "Release to ship"],
        ["Freight and customs", "Per trade terms", "Per trade terms", "Delivery plan"],
        ["Installation and inspection", "Defined supervision / scope", "Site readiness and local labour", "Completion record"],
        ["Operations and maintenance", "Manuals and training", "Daily ownership", "Handover sign-off"],
      ],
      footnote: "The signed contract and responsibility matrix—not the word 'turnkey'—define each party's actual obligations.",
    },
    sources: [sources.cpsc, sources.astmF1918, sources.astmF2970, sources.ada],
    related: [
      { label: "Free 3D indoor play center design", href: "/free-3d-design-for-indoor-play-center" },
      { label: "Indoor playground business plan", href: "/indoor-playground-business-plan" },
      { label: "Family entertainment center business plan", href: "/family-entertainment-center-business-plan" },
      { label: "ASTM trampoline supplier checklist", href: "/astm-certified-commercial-trampoline-park-supplier" },
      { label: "Our design-to-install process", href: "/process" },
    ],
    faq: [
      { title: "What is included in a complete indoor play center solution?", desc: "A defined complete scope can include feasibility, zoning, 3D concept, equipment specification, manufacturing, quality records, logistics coordination, installation support, as-built documents, operator training and spare-parts planning." },
      { title: "Is a turnkey solution the same as one fixed-price contract?", desc: "Not necessarily. 'Turnkey' is often used loosely. The contract must state each deliverable, exclusion, local building interface, trade term, approval and payment milestone." },
      { title: "What remains the owner's responsibility?", desc: "Typical owner-side items include the lease, permits, local professional design, building and fire work, utilities, insurance, staffing, operating procedures and authority approvals unless the contract explicitly says otherwise." },
      { title: "How are multiple equipment categories coordinated?", desc: "Use one controlled layout, capacity plan, circulation strategy, standard matrix and revision register. Each attraction then has its own technical evidence and operating requirements within that shared plan." },
      { title: "What should be handed over before opening?", desc: "Request signed as-built drawings, equipment and parts schedules, applicable evidence, installation records, inspection actions, maintenance manuals, spare-parts list, warranty terms and operator-training records." },
    ],
  },
};
